### ISSUE TITLE
Driver not loaded with kernel 4.14.67-1-lts in ArchLinux

### ISSUE THREAD

**Issue by mb1111** [tbsdtv/media_build#11]
compilation terminated successfully, but on loading driver dmesg shows errors:

[    7.437013] tbsecp3: disagrees about version of symbol dvb_dmxdev_init
[    7.437015] tbsecp3: Unknown symbol dvb_dmxdev_init (err -22)
[    7.437027] tbsecp3: disagrees about version of symbol dvb_ca_en50221_init
[    7.437028] tbsecp3: Unknown symbol dvb_ca_en50221_init (err -22)
[    7.437052] tbsecp3: disagrees about version of symbol dvb_register_adapter
[    7.437052] tbsecp3: Unknown symbol dvb_register_adapter (err -22)
[    7.437060] tbsecp3: disagrees about version of symbol dvb_dmx_swfilter_packets
[    7.437061] tbsecp3: Unknown symbol dvb_dmx_swfilter_packets (err -22)
[    7.437076] tbsecp3: disagrees about version of symbol dvb_dmx_release
[    7.437077] tbsecp3: Unknown symbol dvb_dmx_release (err -22)
[    7.437082] tbsecp3: disagrees about version of symbol dvb_ca_en50221_release
[    7.437083] tbsecp3: Unknown symbol dvb_ca_en50221_release (err -22)
[    7.437089] tbsecp3: disagrees about version of symbol dvb_net_init
[    7.437090] tbsecp3: Unknown symbol dvb_net_init (err -22)
[    7.437096] tbsecp3: disagrees about version of symbol dvb_dmxdev_release
[    7.437097] tbsecp3: Unknown symbol dvb_dmxdev_release (err -22)
[    7.437103] tbsecp3: disagrees about version of symbol dvb_frontend_detach
[    7.437104] tbsecp3: Unknown symbol dvb_frontend_detach (err -22)
[    7.437107] tbsecp3: disagrees about version of symbol dvb_net_release
[    7.437108] tbsecp3: Unknown symbol dvb_net_release (err -22)
[    7.437113] tbsecp3: disagrees about version of symbol dvb_unregister_frontend
[    7.437114] tbsecp3: Unknown symbol dvb_unregister_frontend (err -22)
[    7.437117] tbsecp3: disagrees about version of symbol dvb_register_frontend
[    7.437118] tbsecp3: Unknown symbol dvb_register_frontend (err -22)
[    7.437120] tbsecp3: disagrees about version of symbol dvb_unregister_adapter
[    7.437121] tbsecp3: Unknown symbol dvb_unregister_adapter (err -22)
[    7.437122] tbsecp3: disagrees about version of symbol dvb_dmx_init
[    7.437123] tbsecp3: Unknown symbol dvb_dmx_init (err -22)

**Comment by crazycat69** [comment]
need remove old media modules before install.
see install.sh script

**Comment by mb1111** [comment]
omg, forgot that. Thanks. Drivers work on 4.14 as well as 4.18.5
