### ISSUE TITLE
stid135-fe DTV_SCRAMBLING_SEQUENCE_INDEX wrongly implemented

### ISSUE THREAD

**Issue by tvhdeeptho** [tbsdtv/media_build#13]
According to the linux dvb api v5.11 pls_mode and pls_code should be passed via the 
DTV_SCRAMBLING_SEQUENCE_INDEX  call, but the driver code treats the data
as a binary flag:

	if (p->scrambling_sequence_index) {
		pls_mode = 1;
		pls_code = 0;
	}

See also the discussion in tvheadend.org: 
https://tvheadend.org/issues/5556

Specifically it is not clear in what the content of 
 p->scrambling_sequence_index should be.
tvheadend computes this value from user provided data (e.g., pls_code)
as follows:

uint32_t dvb_sat_pls( dvb_mux_conf_t *dmc )
{
  if (dmc->dmc_fe_pls_mode == DVB_PLS_ROOT) {
    uint32_t x, g;
    const uint32_t root = dmc->dmc_fe_pls_code & 0x3ffff;
    for (g = 0, x = 1; g < 0x3ffff; g++)  {
      if (root == x)
        return g;
      x = (((x ^ (x >> 7)) & 1) << 17) | (x >> 1);
    }
    return 0x3ffff;
  }
  return dmc->dmc_fe_pls_code & 0x3ffff;
}

but clearly the sti135-fe code expect the values as listed on websites such as kingofsat
directly without processing.

```

**Comment by crazycat69** [comment]
fixed, please check
f539dd63c402b8354a37f4c164f5ddd4d589bf9c

**Comment by tvhdeeptho** [comment]
This fix works.

**Comment by tvhdeeptho** [comment]
Unfortunately, I have to reopen this ticket:
your pathc only works for the French channels on 5.0W which use GOLD.

For Rai, which uses ROOT, the driver code (or tvheadend) does the wrong thing. 
tvheadend computes some kind of index x and passes this to the driver 
as  scrambling_sequence_index

uint32_t
dvb_sat_pls( dvb_mux_conf_t *dmc )
{
  if (dmc->dmc_fe_pls_mode == DVB_PLS_ROOT) {
    uint32_t x, g;
    const uint32_t root = dmc->dmc_fe_pls_code & 0x3ffff;

    for (g = 0, x = 1; g < 0x3ffff; g++)  {
      if (root == x)
        return g;
      x = (((x ^ (x >> 7)) & 1) << 17) | (x >> 1);
    }
    return 0x3ffff;
  }
  return dmc->dmc_fe_pls_code & 0x3ffff;
}

In the driver, pls_mode s set to 1 (should be 0) and pls_code is set to x, which has the wrong 
value.

Strangely enough, the card still tunes to the channel eventually but it takes a very long time.

**Comment by crazycat69** [comment]
So this wrong reverse ROOT->GOLD calculation. And waste many times.

You need set Gold code for DTV_SCRAMBLING_SEQUENCE_INDEX
https://www.flysat.com/e5wa.php

For RAI Gold code 131070 (equal to ROOT 16416)

**Comment by tvhdeeptho** [comment]
Carayzca69, 
Thanks for your help.

However, I think still something is not right. Not sure what is the reason, but here is the analysis:

1. If I understand you correctly, I should enter in tvheadend: GOLD and 131070 (instead of  ROOT + 16416). If I do that with the original tvheadend code, and change channels between RAI 1 and RAI2 (same stream), it takes 20 seconds to change channels. So this is a problem.

In this case, tvheadend calls dvb_sat_pls, but because of the gold parameter (instead of root), it just passes  131070 to DTV_SCRAMBLING_SEQUENCE_INDEX. So it should work according to your advice, but 
it works very slowly (and it works equally well/slowly if I use a different value than 131070).

Or did I make a mistake?  Or does tvheadend code have another bug?

2. If I modify the tvheadend code so that it does NOT call 
dvb_sat_ps and therefore NOT call DTV_SCRAMBLING_SEQUENCE_INDEX, then the 
rai channels work and channel changing is  fast (< 2 seconds).

In this "old style" case, tvheadend, basically calls DTV_STREAM_ID with parameter  
(dmc->dmc_fe_stream_id & 0xFF) |  ((dmc->dmc_fe_pls_code & 0x3FFFF)<<8) | ((dmc->dmc_fe_pls_mode & 0x3)<<26).

**Comment by crazycat69** [comment]
I prefer my old way with DTV_STREAM_ID :)
DTV_SCRAMBLING_SEQUENCE_INDEX only for Gold code, reverse Gold->Root searching in application very bad idea.

**Comment by tvhdeeptho** [comment]
tvheadened maintainers might object to changing their code because it might break other cards,
but they could provide a flag to switch between the two systems. It is better to have a setting than
to have no setting, but it is one more reason for users to get confused.
