### ISSUE TITLE
tbs6909x  FE_READ_STATUS takes a long time

### ISSUE THREAD

**Issue by tvhdeeptho** [tbsdtv/media_build#14]
When tuning to multistream transponders on 5.0W (but in rare cases also 
when tuning to regular trnsponders on 28.2E), it seems that the 
following tvheadend code takes a very long time: 1.6 to 3.1 seconds.
I believe it can only be expained by the ioctl taking a long time.

The two calls "dttime(200)" simply check the time between dttime calls, 
and report if this time is larger than 200ms.  Here are typical outputs:
Feb 25 22:20:48 streacom tvheadend[20845]: mpegts: linuxdvb_frontend_monitor_924 TIME: 307
Feb 25 22:21:20 streacom tvheadend[20845]: mpegts: linuxdvb_frontend_monitor_924 TIME: 231
Feb 25 22:21:52 streacom tvheadend[20845]: mpegts: linuxdvb_frontend_monitor_924 TIME: 394
Feb 25 22:22:00 streacom tvheadend[20845]: mpegts: linuxdvb_frontend_monitor_924 TIME: 1995

many calls take more than 200ms (which is already quite long) but some take 1.995 seconds (in the example). The longest I have seen is 3.1 seconds.

`	dttime(200);
  /* Get current status */
  if (ioctl(lfe->lfe_fe_fd, FE_READ_STATUS, &fe_status) == -1) {
    tvhwarn(LS_LINUXDVB, "%s - FE_READ_STATUS error %s", buf, strerror(errno));
    /* TODO: check error value */
    return;

  } else if (fe_status & FE_HAS_LOCK)
    status = SIGNAL_GOOD;
  else if (fe_status & (FE_HAS_SYNC | FE_HAS_VITERBI | FE_HAS_CARRIER))
    status = SIGNAL_BAD;
  else if (fe_status & FE_HAS_SIGNAL)
    status = SIGNAL_FAINT;
  else
    status = SIGNAL_NONE;
	dttime(200); //many times larger than 200ms
`

**Comment by crazycat69** [comment]
This normal behavior, status locking when tuning.

**Comment by tvhdeeptho** [comment]
> This normal behavior, status locking when tuning.

Your reply  agrees with the the statement in the 
docs that FE_TIMEDOUT  means "no lock within the last about 2 seconds",
but the docs do not mention explicitly that it blocks.

tvheadend 4.3 calls this ioctl with a global lock held. This lock is also used when processing SI
data (and probably also for stream data). This means that the whole 
application can block, which causes all kinds of problems.

I assume there is no alternative non-blocking equivalent?

**Comment by perexg** [comment]
> This normal behavior, status locking when tuning.

It's not normal behaviour when the file descriptor is opened with O_NONBLOCK. All syscall should return ASAP without blocking.

**Comment by tvhdeeptho** [comment]
@perexg 
I doubt that what you say is correct. O_NONBLOCK affects read and write. Nothing else

This is what the man page of open says:
       O_NONBLOCK or O_NDELAY
              When  possible,  the  file is opened in nonblocking mode.  Neither the open() nor any subsequent opera‐
              tions on the file descriptor which is returned will cause the calling process to wait.

=> This could make you believe that ioctl will not block, but continue reading...

              Note that this flag has no effect for regular files and block devices; that  is,  I/O  operations  will
              (briefly)  block  when  device  activity  is  required, regardless of whether O_NONBLOCK is set.  Since
              O_NONBLOCK semantics might eventually be implemented, applications  should  not  depend  upon  blocking
              behavior when specifying this flag for regular files and block devices.

=> So there is not even a guarantee in general 

However, other manpages for "open" say something slightly different:

When opening a block special or character special file that supports non-blocking opens:
    If O_NONBLOCK is set, the open() function shall return without blocking for the device to be ready or available. Subsequent behavior of the device is device-specific.
    If O_NONBLOCK is clear, the open() function shall block the calling thread until the device is ready or available before returning.
Otherwise, the behavior of O_NONBLOCK is unspecified.

=> So this means: "only the open call itself can be assumed to return immediately" (which 
is rather pointless)

In any case, in general there are no guarantees. So one has to consult the specific
dvbapi documentation. That does not mention anything about ioctls behaviour. 

Both the generic ioctl manpages and linuxdvbapi however clearly list the possible
errors returned by ioctl. Noteworthy is that EWOULDBLOCK and EGAIN are never
mentioned. How is an ioctl then supposed to inform the caller about the fact that it 
did not fail, but simply returned in order to not block?

My conclusion is that the blocking behaviour of ioctl is not specified, so it can block
and it probably does block.

**Comment by perexg** [comment]
Okay, I got it. So it's upon the API how this flag is interpreted. Unfortunately, the DVB API is a bit vague about this, but looking to the current kernel, **NO DRIVERS** are blocking during this status ioctl and only few of them set the FE_TIMEDOUT flag (all set it based on the status read from the hardware - no timers), so we can call it nearly as obsolete, thus the 2 seconds waiting is not recommended. All applications usually has own signal / lock wait loop, thus doing this in the driver does not make much sense. This ioctl should return ASAP.
