### ISSUE TITLE
tbs6909x powersave

### ISSUE THREAD

**Issue by tvhdeeptho** [tbsdtv/media_build#15]
tbs6909x has 8 tuners. 
I enable only tuner 0 and 1, and activate powersave on both tuners.
With this combination I can watch a channel on one transponder (e.g., Vertical high band)
and a second channel on another tranponder (same band and polarisation).

If I stop the channel stream on tuner 1, then also the live picture on channel 0 stops.
If I restart the channel stream on tuner1, the live stream on channel0 restarts.

What happens is that tvheadend  close the frontend for tuner 1. At this stage tuner 0 stops
functioning. If I prevent tvheadend from closing the frontend by commenting out code, the stream
on tuner 0 continues to work.

Is this a driver bug?
What is the proper way to ensure maximal powersave?

By the way, when measuring the power consumption with a meter, I do not see much 
difference with or without powersave. The chips also remain warm.

**Comment by crazycat69** [comment]
what LNB connection mode selected (stid135 mode option) ?

**Comment by tvhdeeptho** [comment]
cat /etc/modprobe.d/stid135.conf
options stid135 mode=1

So tuners 0,2,4,6 operate independently.
Tuners 1,3,5,7 are slave tuners.

**Comment by crazycat69** [comment]
No any slave tuners, each pair can control LNB voltage on same input.
So you must setup tuner 0 as mater in TVH, tuner 1 as slave to tuner 0.

**Comment by tvhdeeptho** [comment]
I understand that bioth tuners are quivalent to the driver (not a problem), but for tvheadend
the terminology is master and slave.

What you propose is exactly what I set up. and that is what does not work. closing tuner 1 
seems to also affect something on tuner 0. I did not check the electrical level, but the stream 
on tuner 0 stops when the stream on tuner 1 is stopped and the streamon tuner 0 returns when
tuner1 is tuned again.

**Comment by crazycat69** [comment]
Look like stid135_sleep() turn-off tuner cell in mode 1
https://github.com/tbsdtv/linux_media/blob/latest/drivers/media/dvb-frontends/stid135/stid135-fe.c#L703

Disable power-save in tvh

**Comment by tvhdeeptho** [comment]
Yes, this is what happens and it is a bug in the drivers.

You can also verify as follows: start kaffeine as user A. 
Configure it to use the 7th adapter (not clear in kaffeine user interface; must be careful).
Also configure it to use diseqc. Perform channel scan. Tune to some channel. Channel plays

Now login as second user B (because kaffeine refuses to start more than once as same user)
Configure it to use the 8th adapter. Configure it to NOT user diseqc. Start a channel scan.
Of course this will find only transponders with same frequency and polarisation as user A.
Now tune to a channel on a different transponder. Video plays. Video also still plays for 
user A. 

Stop kaffeine for user B (stop the program; it is NOT enough to stop the stream).
The video also stops for user A.

Wait a while. User B now starts kaffeine again and plays a channel. This works. At the same 
time the video starts working again for user A.

**Comment by crazycat69** [comment]
This not bug, just side effect from default dvb-core behavior:
$ modinfo dvb-core
filename:       /lib/modules/4.4.0-138-generic/kernel/drivers/media/dvb-core/dvb-core.ko
license:        GPL
author:         Marcus Metzler, Ralph Metzler, Holger Waechtler
description:    DVB Core Driver
...................
**parm:           dvb_powerdown_on_sleep:0: do not power down, 1: turn LNB voltage off on sleep (default) (int)**
parm:           dvb_mfe_wait_time:Wait up to <mfe_wait_time> seconds on open() for multi-frontend to become available (default:5 seconds) (int)
..................

So just add dvb-core option to /etc/modprobe.d/dvb.conf:
**options dvb-core dvb_powerdown_on_sleep=0**

**Comment by tvhdeeptho** [comment]
This is not really a solution as it leaves the lnb powered on when no power is needed.

I think the driver should be clever enough to only turn off lnb power when power is not needed by tuner 0 and tuner 1.  It is what the user expects. If one of the tuners is still streaming, its hardware should
not be put to sleep.

**Comment by crazycat69** [comment]
So you need card with independed tuner/demods like tbs 6902, 6903, 6903x, 6904, 6904x.
6909/6909x designed for iptv streamers in default  mode 0.
mode 1 is optional and have reasonable restrictions.

**Comment by tvhdeeptho** [comment]
4 tuners is enough for me.  If I wanted 8, I would just install my other tbs card in a second pci slot.

The 4 slave ones are nice to have, but I still believe  the driver should handle this case more cleverly and power down the lnb only if both adapter devices are not open.

**Comment by tvhdeeptho** [comment]
The attached patch fixes this bug and powers down a tuner only when no modulator is 
using it.
[sleep_patch.txt](https://github.com/tbsdtv/media_build/files/2980536/sleep_patch.txt)
