### ISSUE TITLE
tbs6909x multistream stops functioning after days of use

### ISSUE THREAD

**Issue by tvhdeeptho** [tbsdtv/media_build#16]
I have noticed that sometimes that sometimes the drivers enter a state in which multistream on the RAI channels on 5.0W stops functioning: channels do not tune, or after tuning there are lots of picture errors (half the screen is green). This happens usually one or two days after rebooting the 
system (it is permanently on).

The tvheadend logs show continuity counter errors (see below). 
Restarting kodi/tvheadend has no effect, but after a reboot everything returns to normal
and all channels function well.

 In all cases, snr is bout 12-12.5dB depending on the transponder. Also, tvheadend is NOT epg-grabbing at this time (so it is probably not directly related to other continuity pcounter errors reported on the tvheadend issue tracker).

The fact that the problem is not fixed by restarting tvheadend, but is fixed by a reboot leads me to believe that the problem is in the drivers or in the firmware.

tvheadend version: 4.3

Mar  3 20:44:27 streacom tvheadend[10009]: mpegts: mtimer_thread_731 TIME: 819
Mar  3 20:44:27 streacom tvheadend[10009]: TS: 5.0W/11179V/Rai 1 HD: H264 @ #438 Continuity counter error (total 1)
Mar  3 20:44:27 streacom tvheadend[10009]: TS: 5.0W/11179V/Rai 1 HD: AC3 @ #449 Continuity counter error (total 1)
Mar  3 20:44:27 streacom tvheadend[10009]: TS: 5.0W/11179V/Rai 1 HD: TELETEXT @ #588 Continuity counter error (total 1)
Mar  3 20:44:27 streacom tvheadend[10009]: parser: 5.0W/11179V/Rai 1 HD: AC3 @ #449: DTS and PCR diff is very big (3631523790)
Mar  3 20:44:29 streacom tvheadend[10009]: TS: 5.0W/11179V/Rai 1 HD: MPEG2AUDIO @ #450 Continuity counter error (total 1)
Mar  3 20:44:29 streacom tvheadend[10009]: tbl-eit: eit: 11179V in 5.0W: invalid checksum (len 205, errors 1)
Mar  3 20:44:30 streacom tvheadend[10009]: parser: 5.0W/11179V/Rai 1 HD: AC3 @ #449: DTS and PCR diff is very big (3631380155)
Mar  3 20:44:31 streacom tvheadend[10009]: tbl-base: sdt: 11179V in 5.0W: invalid checksum (len 327, errors 1)

**Comment by tvhdeeptho** [comment]
The kernel log shows some messages (attached) 
which show a lot of suppressed  dvb_dmx_swfilter_packet callbacks.

**Comment by crazycat69** [comment]
but usual DVB-S2 CCM or DVB-S transponders work ok ?

**Comment by tvhdeeptho** [comment]
DVB-S2 and dvb-s remain working indeed.

I tried reloading the modules with "make rmmod; make insmod"
but this does not work. Reboot helps.

**Comment by tvhdeeptho** [comment]
Today I was able to trigger the problem by tuning to rai 2, and then starting tvheadends 
OTA epgrabber. After it gets into the bad state, it remains like that (even restarting tvheadend
does not help).
Unloading/reloading the driver as follows brings back the picture:
sudo modprobe -r tbsecp3
sudo modprobe tbsecp3

It is not possible to reliably reproduce the issues with the OTA epg grabber: picture often 
remains good, but messages likes these keep appearing:
dvb_dmx_swfilter_packet: 131 callbacks suppressed
When the problem is really bad, the numbers are higher:
dvb_dmx_swfilter_packet: 2077 callbacks suppressed

**Comment by tvhdeeptho** [comment]
The source of the dvb_dmx_swfilter_packet ... callbacks suppressed error is
dvb_demux: dvb_dmx_swfilter_packet: TS packet counter mismatch. PID=0x1f40 expected 0xb got 0xc
This is while the picture is still good.

dvb_dmx_swfilter_packet is called from dvb_dmx_swfilter_packets,
which is called from tbsecp3_dma_tasklet.

Either tbs_read reads bad data or there is some bug in tbsecp3_dma_tasklet

**Comment by tvhdeeptho** [comment]
I have double checked the code in tbsecp3_dma_tasklet. and cannot find any errors. 
The conclusion is obvious: the data transferred over DMA has packets missing.

I also notice that dvb_dmx_swfilter_packet receives packets for pids not requested from the user application. Does this mean that per tuner a complete transport stream is sent from the card
to the tuner? If so, then 4 active tuners means that a huge amount of data is passed over the 
pcie bus. This could easily amount to 100 Mbit/second with 4 active tuners.

I would expect that the card itself filter the PIDs (hardware pid filtering) 
so that the rest of the system (the kernel) is relieved of this work. Am I missing something?

**Comment by crazycat69** [comment]
This very strange issue. Maybe related to FPGA firmware.
You use all 8 demods ?

Released 6909x use special transfer mode 8xTS over one parallel bus from STiD135 (each TS packet tagged and parsed by FPGA).+LDPC decoder inside STiD135 have some limitation, so possible use all 8 demods with maximum 8PSK,30000Ks

**Comment by tvhdeeptho** [comment]
I use only 4 demods. Operated independently (mode 1)

Additional info: 
In some cases, the messages are false alerts
-after channel change, always these errors occur briefly on the new stream. I disregard those.
-on some transponders, for example 23.5E, 11856.00V, there are always such errors on pids
0x1f40 and 0x1f41 (never any other). I believe this could be a corrupt stream being transmitted. 
I disregard those. It could mean that other transponders also transmit streams with errors on some 
pids (e.g., on 23.5E it is an irdeto stream)

The real problem  can sometimes be made visible as follows:
-one tuner tunes to 5.0W e.g, Rai movie. The only errors which occur are on pids which are not 
used. So the picture is perfect
-I then launch a second connection via tvheadend webinterface 
to channel TRP1 (28.2E, 11425H). This is the UK freesat 
transponder. The TRP1 channel is encrypted (I cannot watch it), and it seems to be very high bit rate
(8 MBit/s). At this point, I start seeing not only continuity errors on unused pids, but sometimes 
also on the pids of RAI it self in the kernel log. 

However it is very difficult  to reproduce like this. A lot of tuning (e..g. epggrab) helps, but makes 
it a lot more difficult to analyse the logs.

I sometimes see some picture corruption. And tvheadend also reports errors. The errors in tvheadend do not always coincide with kernel errors. This is probably is because of bugs tvheadend, so we must be careful to not blame the drivers for all problems...

In the mean time, I also made two changes to my system: 
Added the options (just to see if it makes a difference)
options stid135 mode=1  dma_pkts=256,256,256,256,256,256,256,256

Turned of linux  pcie_aspm=off (as I noticed "corrected" pcie errors). My first experiment 
made the tbs driver completely lock up. After changing some bios settings this problem was solved.

I will upload my kernel logs. 

At the end of the messages you can see "dt=0" or "dt=1". dt=1 means that the pid is requested 
by user space. "dt=0" means that it is not requested.

dvb_demux: dvb_dmx_swfilter_packet: TS packet counter mismatch. PID=0xc20 expected 0xf got 0x0 dt=0

I will also upload my tvheadend log. It can help to find out when tuning takes place (compare the 
time stamps)

**Comment by tvhdeeptho** [comment]
These logs show some of the continuity counter messages. Not sure if there are any real ones
(not false alerts) inside. tvheadend only reports errors on trp1, but none of rai movies in this
example.  I did not check yet if the driver errors are false errors yet ("false error" means 
errors at the start of tuning when the stream is perhaps not yet stable)

I will need to wait until the problem occurs  to have a more clear report

[kernel.log](https://github.com/tbsdtv/media_build/files/2933657/kernel.log)
[tvheadend.log](https://github.com/tbsdtv/media_build/files/2933658/tvheadend.log)

**Comment by crazycat69** [comment]
**dma_pkts** is **tbsecp3** option

**Comment by Davin622** [comment]
HI tvhdeeptho,
We are  doing the test according to you said, Would you mind email to us(support@tbsdtv.com or Davin@tbsdtv.com). and describe the test steps. help us reappear the problem.

Thanks

**Comment by tvhdeeptho** [comment]
I will contact you by email. Note that I see many different issues,which could be related.
1. continuity errors just after tuning. These happen with each tune, but they don't last long.
They probably should not happen, but they cause little problems

2. continuity counter errors on two specific streams on a transponder on 23.5V. These happen
always. It is possible that this is a problem with the transponder and not with the card (it only happens
on 1 or 2 transponders on 23.5V). 
3. continuity counter errors not related to tuning. These are very difficult to reproduce, and the 
logs can become confusing because of problem 1 (epg grabbing). The way I finally reproduced
them, and which I advise to try:
-activate 4 tuners (0,2,4,6). Disable the others
-start viewing one channel
-use tvheadend to start 3 streams on 3 other transponders or start recording 3 streams .
This way  tvheadend will not start tuning for epgrab. It may be best to take multistream channels for
this experiment (I don't know, but I used 2 multistreams and 2 others)
-now start channel changing the live stream. Gradually I start to see problems (errors in the
picture and errors in the logs). The multistreams seem to have the biggest problems (not sure), but 
I found one case where a regular dvb-s2 channel (ITV HD)  was completely unwatchable. tvheadend
webinterface shows very high bit error rate.

The attached log is a mixture of the tvheadend log and the kernel debug log, sorted by timestamp.
This helps to see the time order of problems.

Look for: Mar  6 20:20:31. Tuning to ITV HD starts and 3 channels are running in the background.

-channel TF1 starts showing errors in tvheadend,

Mar  6 20:20:33
[log20190306.log](https://github.com/tbsdtv/media_build/files/2938048/log20190306.log)

-ITV HD also shows errors in kernel debug loog: PID=0x915. This could be problem 1 or 3.
-tvheadend also shows problems on this channel

Mar  6 20:20:38
-ITV still shows problems in driver
This continues until 20:21:18
At this point I stop the three background streams (TF1, PBS, Italia1)

Mar  6 20:21:38
The kernel keeps showing many errors on itvh hd

After this, I disable all tuners, except for the one which runs ITV HD. I then manage
to retune and have a perfect picture. This proves that the sattelite equipment is working.

At the end of the log, 







-

**Comment by tvhdeeptho** [comment]
About problem 2: I verified that a tbs 5990 card also sees continuity errors in 
on 23.5E, 11856.00V,  in the streams with pid 0x1f40 and 0x1f41.  It would be 
interesting to do the same test with a non-tbs card (I don't have any)

I suspect the error is in the stream. Note that the 5990 seems to also produce discontinuities
on more pids. If I make the analysis time longer, those errors remain at a low level, but 
the ones on streams 0x1f40 and 0x1f41 increase. So I think both cards are fine, but there
is a problem in the stream.

The experiment was done with tsduck. Nice prorgam...


#tbs 5990 - short
tsp -I dvb -a 8 --delivery-system DVB-S2 --frequency 11856000000 --polarity V --symbol-rate  29900000 --fec 2/3 --satellite-number 1 -P until --seconds 20|tsanalyze --error-analysis
TITLE: ERROR ANALYSIS REPORT
INFO: Transport Stream Identifier: 3208 (0x0C88)
TS:3208:0x0C88: TS packets with transport error indicator: 27
TS:3208:0x0C88: Unreferenced PID's: 3
TS:3208:0x0C88: No BAT
PID:36:0x0024: Discontinuities (unexpected): 1
PID:116:0x0074: Discontinuities (unexpected): 1
PID:514:0x0202: Discontinuities (unexpected): 1
PID:516:0x0204: Discontinuities (unexpected): 1
PID:518:0x0206: Discontinuities (unexpected): 3
PID:523:0x020B: Discontinuities (unexpected): 2
PID:527:0x020F: Discontinuities (unexpected): 2
PID:540:0x021C: Discontinuities (unexpected): 1
PID:556:0x022C: Discontinuities (unexpected): 2
PID:557:0x022D: Discontinuities (unexpected): 1
PID:560:0x0230: Discontinuities (unexpected): 2
PID:564:0x0234: Discontinuities (unexpected): 2
PID:7276:0x1C6C: Invalid scrambling control values: 1
PID:8000:0x1F40: Discontinuities (unexpected): 7
PID:8001:0x1F41: Discontinuities (unexpected): 8
SUMMARY: Error count: 18

#tbs 5990 - long
tsp -I dvb -a 8 --delivery-system DVB-S2 --frequency 11856000000 --polarity V --symbol-rate  29900000 --fec 2/3 --satellite-number 1 -P until --seconds 60|tsanalyze --error-analysis
TITLE: ERROR ANALYSIS REPORT
INFO: Transport Stream Identifier: 3208 (0x0C88)
TS:3208:0x0C88: TS packets with transport error indicator: 27
TS:3208:0x0C88: suspect TS packets, ignored: 1
TS:3208:0x0C88: Unreferenced PID's: 2
TS:3208:0x0C88: No BAT
PID:32:0x0020: Discontinuities (unexpected): 1
PID:83:0x0053: Discontinuities (unexpected): 1
PID:88:0x0058: Discontinuities (unexpected): 1
PID:94:0x005E: Discontinuities (unexpected): 1
PID:96:0x0060: Discontinuities (unexpected): 1
PID:514:0x0202: Discontinuities (unexpected): 2
PID:516:0x0204: Discontinuities (unexpected): 2
PID:518:0x0206: Discontinuities (unexpected): 2
PID:523:0x020B: Discontinuities (unexpected): 2
PID:527:0x020F: Discontinuities (unexpected): 1
PID:540:0x021C: Discontinuities (unexpected): 1
PID:556:0x022C: Discontinuities (unexpected): 2
PID:557:0x022D: Discontinuities (unexpected): 2
PID:558:0x022E: Discontinuities (unexpected): 1
PID:561:0x0231: Discontinuities (unexpected): 1
PID:564:0x0234: Discontinuities (unexpected): 1
PID:585:0x0249: Discontinuities (unexpected): 2
PID:8000:0x1F40: Discontinuities (unexpected): 33
PID:8001:0x1F41: Discontinuities (unexpected): 28
SUMMARY: Error count: 23


#tbs 6990x short 
tsp -I dvb -a 6 --delivery-system DVB-S2 --frequency 11856000000 --polarity V --symbol-rate  29900000 --fec 2/3 --satellite-number 1 -P until --seconds 20|tsanalyze --error-analysis
TITLE: ERROR ANALYSIS REPORT
INFO: Transport Stream Identifier: 3208 (0x0C88)
TS:3208:0x0C88: Unreferenced PID's: 2
TS:3208:0x0C88: No BAT
PID:8000:0x1F40: Discontinuities (unexpected): 8
PID:8001:0x1F41: Discontinuities (unexpected): 4
SUMMARY: Error count: 4

tbs 6909x - long
tsp -I dvb -a 6 --delivery-system DVB-S2 --frequency 11856000000 --polarity V --symbol-rate  29900000 --fec 2/3 --satellite-number 1 -P until --seconds 60|tsanalyze --error-analysis
TITLE: ERROR ANALYSIS REPORT
INFO: Transport Stream Identifier: 3208 (0x0C88)
TS:3208:0x0C88: Unreferenced PID's: 2
TS:3208:0x0C88: No BAT
PID:8000:0x1F40: Discontinuities (unexpected): 33
PID:8001:0x1F41: Discontinuities (unexpected): 22
SUMMARY: Error count: 4

**Comment by tvhdeeptho** [comment]
Additional information: right now, tuner 4 has trouble receiving a multistream, but it works 
fine on any other transponder. The bit error rate in tvheadend is huge. Restarting tvheadend
does not help.

Interestingly, if I configure tuner 5 with exactly the same configuration as 4, the multistream works 
on tuner 5.

So this problem is a per tuner problem.

**Comment by crazycat69** [comment]
Please check latest changes - media_build and linux_media updated for 4.20.x-5.0.x compatibility + minor changes in stid135 (possible related to multistream reception).

**Comment by tvhdeeptho** [comment]
New info: today I was experimenting on RAI4. I succeeded in making the multi stream fail
by lots of epg grabbing. 

As usual, I can "fix" the problem by unloading and then reloading 
the tbsecp3 module (and a corresponding restart of tvheadend).

In this particular example, I noticed that the signal level is much higher (-27 dBm) when the 
problem occurs, then in normal use (-37 dBm).  

According to the kernel lock, the tuner is not locked when the problem occurs (in 
this example):
stid135_set_parameters: not locked, band rf_power -27 dBm !

What we see could either be the tuner trying to adjust the AGC to achieve a lock or 
it could be what causes the problem.

In other cases, I did see a distorted picture which shows that the tuner then was tuning 
to the right frequency and therefore had locked. In this case the signal levels are normal.

In some cases, the driver reports:
 stid135_set_parameters: not locked, band rf_power 9 dBm !

So now this is a positive number. It does not make much sense.

**Comment by tvhdeeptho** [comment]
Some more info, by adding some logging to 	fe_stid135_search, I have some 
more info about the pParams->demod_results  which is returnded from that function,
The logged message are in the following path

else if(((signalType == FE_SAT_RANGEOK) 
				|| ((satellitte_scan > 0) 
				&& (signalType == FE_SAT_NODATA))) 
				&& (pParams->handle_demod->Error == CHIPERR_NO_ERROR))
				{

When the problem occurs on the multistream on 5.0W containing the Italian Paramount channel, the tuner is locked` and I get the following results, which show the similarities and differences for 
good and bad streams. A good stream is one with good picture, A bad stream yields a mostly
green picture, with a few random blocks with real image popping up. Sometimes tvheadend
has trouble tuning, which affects the logs. The log files are attached. Initially several tuners were
active, but when the problem started, I disabled all of them, except one. Then I started channel
switching. The picture never comes back, until I reload the driver modules. The last part of the log
shows certainly good results.

My observations:
- there are no clear distinctions between a good and a bad stream
-some values seem to vary randomly: puncture_rate, modcode, frame_length, roll_off, modulation
Perhaps they are never read properly, or perhaps this is related to the ACM/VCM modulation

Interpreting the logs takes some time. This is my summary of the essential tuning results.

#good stream  (?)
Mar 17 21:46:34 streacom kernel: [156768.023344] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1944391 symbol_rate=34199303 puncture_rate=4 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=2 modulation=1 error=0

#??? tvheadend problem
Mar 17 21:46:46 streacom kernel: [156780.137248] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942392 symbol_rate=34199111 puncture_rate=1 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=2 modulation=1 error=0

#immediate unsupscription, slow tvheadend?
Mar 17 21:47:11 streacom kernel: [156805.266819] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942389 symbol_rate=34198975 puncture_rate=0 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=0 modulation=1 error=0

#good stream (?_
Mar 17 21:47:27 streacom kernel: [156821.514515] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942395 symbol_rate=34199227 puncture_rate=1 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=0 modulation=1 error=0

#bad stream
Mar 17 21:48:24 streacom kernel: [156878.519434] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942385 symbol_rate=34199019 puncture_rate=1 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=0 modulation=1 error=0

#bad stream
Mar 17 21:48:32 streacom kernel: [156886.789850] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942387 symbol_rate=34199226 puncture_rate=0 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=2 modulation=1 error=0

#bad stream
Mar 17 21:49:28 streacom kernel: [156942.356732] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942388 symbol_rate=34199281 puncture_rate=0 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=0 modulation=1 error=0

#definitely bad stream
Mar 17 21:50:22 streacom kernel: [156996.350870] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942392 symbol_rate=34199333 puncture_rate=1 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=2 modulation=1 error=0

#definitely bad stream
Mar 17 21:51:00 streacom kernel: [157034.150800] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942396 symbol_rate=34199317 puncture_rate=1 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=2 modulation=1 error=0

#definitely bad stream
Mar 17 21:51:26 streacom kernel: [157060.362388] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942394 symbol_rate=34199179 puncture_rate=1 modcode=0 pilots=0 frame_length=1 spectrum=1 roll_off=2 modulation=14 error=0


#After module reload. Definitely good result
Mar 17 21:52:31 streacom kernel: [157125.079938] fe_stid135_search: DEEPTHO2: locked=1 standard=1 frequency=1942395 symbol_rate=34199274 puncture_rate=0 modcode=16 pilots=0 frame_length=0 spectrum=1 roll_off=0 modulation=1 error=0




[kernel.txt](https://github.com/tbsdtv/media_build/files/2975759/kernel.txt)
[tvheadend.txt](https://github.com/tbsdtv/media_build/files/2975760/tvheadend.txt)

**Comment by tvhdeeptho** [comment]
Today I experienced problems on tuner0 (but tuner1 was functioning properly).
This time I had a partial picture (watchable with many errors) and I managed
to capture transport streams for two different stream_ids. 

tsanalyze shows that many streams have packets missing

[badstream4.txt](https://github.com/tbsdtv/media_build/files/2990111/badstream4.txt)
[badstream12.txt](https://github.com/tbsdtv/media_build/files/2990112/badstream12.txt)

**Comment by tvhdeeptho** [comment]
For future reference: all of the above was with linux_media  f539dd63c402b8354a37f4c164f5ddd4d589bf9c
stid135-fe: Set Gold code.

I will now update drivers, but note that the problem is more general than multistream:
it can occur for any modulation (or sometimes even: all modulations)

**Comment by tvhdeeptho** [comment]
The attached patch makes this issue go away and also seems to lead to much faster tuning
in tvheadend. I have verified by activating all 8 tuners and then letting tvheadend perform
epg grabs. Without the patch, multistreams stop functioning typically after
1 epg scan. With the patch, I have now reached 4 epg scans without problems.

It is however not clear why it works. It prevents some code being executed concurrently 
with other threads during tuning. The protected calls are
 fe_stid135_get_band_power_demod_not_locked
and
fe_stid135_set_mis_filtering

It is not clear why this protection is needed: fe_stid135_set_mis_filtering accesses different
registers when tuning different demodulators and should be safe even though it accesses
functions like ChipSetField which are not atomic.

fe_stid135_get_band_power_demod_not_locked is a very complex function, which also 
SETS registers. So it might contain errors, but I cannot find anything obviously wrong with it.

It would be good to find the underlying problem, which could be more general than what is described
in this ticket


Because the call is not atomic, it should be protected by a mutex. Otherwise, one thread may 
overwrite a bitfield set by another thread. Concretely what probably goes wrong is the call
 fe_stid135_set_mis_filtering


[multistream_patch.txt](https://github.com/tbsdtv/media_build/files/3005717/multistream_patch.txt)

**Comment by crazycat69** [comment]
Thanks :)
https://github.com/tbsdtv/linux_media/commit/21d7a283021b02711e7dc4dbcc1fff46dbe16ebc

**Comment by tvhdeeptho** [comment]
Just one more comment: in the mean time I verified that it is NOT the call fe_stid135_set_mis_filtering
that goes wrong. It is not atomic, but different "tunes" access different registers and this seems to 
work fine. The problem is therefore in fe_stid135_get_band_power_demod_not_locked

So the patch is still fine, but the cause of the problem is a little narrowed down.

**Comment by Neolo** [comment]
Don't bother, TBS is recalling all 6909X models as of now, as power supply components are faulty in 6909X. I have the same problems with multistreams. I hoped it's a driver related, but I start believe it's not. Contact their support for replacement, there is v2 of the hardware build is coming of this model, addressing the issue (**I very hope so**!!).
