### ISSUE TITLE
Trouble with tbs6909x mode 1

### ISSUE THREAD

**Issue by StormOli** [tbsdtv/media_build#17]
I'm trying to use my 6909x in mode 1 but it's behaving like it is in mode 0

I've added "options stid135 mode=1" to /etc/modprobe.d/stid135.conf and it seems to be picked up

```
oli@tvheadend:~$ modprobe -c | grep stid135
options stid135 mode=1
alias symbol:stid135_attach stid135
```

I'm not sure how to tell what mode the card is in. When I try to scan 11426 H 27500 on adapter 4 then it works.  When I try on adapter 0 then I get the following

```
[Mar 6 15:24] media: Linux media interface: v0.10
[  +0.004878] videodev: Linux video capture interface: v2.00
[  +0.000002] WARNING: You are using an experimental version of the media stack.
                As the driver is backported to an older kernel, it doesn't offer
                enough quality for its usage in production.
                Use it with care.
              Latest git patches (needed if you report a bug to linux-media@vger.kernel.org):
                f539dd63c402b8354a37f4c164f5ddd4d589bf9c stid135-fe: Set Gold code.
[  +0.020572] WARNING: You are using an experimental version of the media stack.
                As the driver is backported to an older kernel, it doesn't offer
                enough quality for its usage in production.
                Use it with care.
              Latest git patches (needed if you report a bug to linux-media@vger.kernel.org):
                f539dd63c402b8354a37f4c164f5ddd4d589bf9c stid135-fe: Set Gold code.
[  +0.016202] TBSECP3 driver 0000:00:02.0: TurboSight TBS 6909x (Octa DVB-S/S2/S2X)
[  +0.004560] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.127799] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:90
[  +3.041874] i2c i2c-0: stid135_probe: cut 2.1
[  +0.000004] i2c i2c-0: stid135_probe: 8xTS to STFE mode init.
[  +0.081884] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000009] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 0 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000210] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.125359] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:91
[  +0.000036] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000005] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 1 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000304] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.109397] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:92
[  +0.000035] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000005] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 2 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000226] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.111401] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:93
[  +0.000029] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000004] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 3 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000439] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.106886] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:94
[  +0.000028] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000004] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 4 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000210] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.105668] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:95
[  +0.000027] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000005] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 5 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000208] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.102695] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:96
[  +0.000190] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000006] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 6 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000215] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.101258] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:97
[  +0.000030] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000005] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 7 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000239] TBSECP3 driver 0000:00:02.0: TurboSight TBS 6909x (Octa DVB-S/S2/S2X): PCI 0000:00:02.0, IRQ 36, MMIO 0xc0040000
[Mar 6 15:25] TBSECP3 driver 0000:00:02.0: DVB: adapter 7 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.243433] TBSECP3 driver 0000:00:02.0: DVB: adapter 6 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.240720] TBSECP3 driver 0000:00:02.0: DVB: adapter 5 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.240146] TBSECP3 driver 0000:00:02.0: DVB: adapter 4 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.247932] TBSECP3 driver 0000:00:02.0: DVB: adapter 3 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.240092] TBSECP3 driver 0000:00:02.0: DVB: adapter 2 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.494622] TBSECP3 driver 0000:00:02.0: DVB: adapter 1 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.236591] TBSECP3 driver 0000:00:02.0: DVB: adapter 0 frontend 0 frequency 0 out of range (950000..2150000)
[Mar 6 15:29] TBSECP3 driver 0000:00:02.0: TurboSight TBS 6909x (Octa DVB-S/S2/S2X)
[  +0.007210] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.129694] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:90
[  +2.965769] i2c i2c-0: stid135_probe: cut 2.1
[  +0.000002] i2c i2c-0: stid135_probe: 8xTS to STFE mode init.
[  +0.075965] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000008] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 0 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000182] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.123813] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:91
[  +0.000016] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000003] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 1 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000192] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.106705] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:92
[  +0.000017] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000005] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 2 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000230] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.109607] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:93
[  +0.000009] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000004] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 3 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000189] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.107467] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:94
[  +0.000009] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000004] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 4 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000193] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.108135] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:95
[  +0.000009] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000003] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 5 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000177] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.107445] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:96
[  +0.000008] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000004] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 6 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000185] dvbdev: DVB: registering new adapter (TBSECP3 DVB Adapter)
[  +0.106961] TBSECP3 driver 0000:00:02.0: MAC address 00:22:ab:92:1a:97
[  +0.000018] i2c i2c-0: STiD135 Multistandard demod found at adr 68 on i2c-0
[  +0.000005] TBSECP3 driver 0000:00:02.0: DVB: registering adapter 7 frontend 0 (TurboSight TBS 6909x (Octa DVB-S/S2/S2X))...
[  +0.000219] TBSECP3 driver 0000:00:02.0: TurboSight TBS 6909x (Octa DVB-S/S2/S2X): PCI 0000:00:02.0, IRQ 36, MMIO 0xc0040000
[Mar 6 15:30] TBSECP3 driver 0000:00:02.0: DVB: adapter 7 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.232035] TBSECP3 driver 0000:00:02.0: DVB: adapter 6 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.243779] TBSECP3 driver 0000:00:02.0: DVB: adapter 5 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.236083] TBSECP3 driver 0000:00:02.0: DVB: adapter 4 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.236653] TBSECP3 driver 0000:00:02.0: DVB: adapter 3 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.239775] TBSECP3 driver 0000:00:02.0: DVB: adapter 2 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.490598] TBSECP3 driver 0000:00:02.0: DVB: adapter 1 frontend 0 frequency 0 out of range (950000..2150000)
[  +0.236423] TBSECP3 driver 0000:00:02.0: DVB: adapter 0 frontend 0 frequency 0 out of range (950000..2150000)
[ +21.409885] i2c i2c-0: delivery_system=5 modulation=0 frequency=1676000 symbol_rate=27500000 inversion=2 stream_id=-1
[  +0.004269] i2c i2c-0: stid135_set_parameters: set pls_mode 0, pls_code 1 !
[  +0.227106] i2c i2c-0: stid135_set_parameters: locked !
[  +0.000004] i2c i2c-0: stid135_set_parameters: disable ISI filtering !
[  +2.317137] i2c i2c-0: delivery_system=5 modulation=0 frequency=1676000 symbol_rate=27500000 inversion=2 stream_id=-1
[  +0.002209] i2c i2c-0: stid135_set_parameters: set pls_mode 0, pls_code 1 !
[  +0.227943] i2c i2c-0: stid135_set_parameters: locked !
[  +0.000003] i2c i2c-0: stid135_set_parameters: disable ISI filtering !
[  +7.366090] i2c i2c-0: delivery_system=5 modulation=0 frequency=1676000 symbol_rate=27500000 inversion=2 stream_id=-1
[  +0.002361] i2c i2c-0: stid135_set_parameters: set pls_mode 0, pls_code 1 !
[  +0.227202] i2c i2c-0: stid135_set_parameters: locked !
[  +0.000003] i2c i2c-0: stid135_set_parameters: disable ISI filtering !
```

**Comment by StormOli** [comment]
I think the problem I'm having is actually mapping the Slaves to their Master. I would have expected 0 to be the master of 1 but this is not the case.  I have Identified the 4 master adapters but how do I know what their corresponding slave adapter is?  I've discovered the master adapters by attempting to scan the same Mux from each adapter.  The results are below

0 Fail
1 Fail
2 Fail
3 Scan
4 Scan
5 Scan
6 Fail
7 Scan

**Comment by crazycat69** [comment]
**options dvb-core dvb_powerdown_on_sleep=0**

**Comment by StormOli** [comment]
I'm not having an issue with them powering down (I don't think) - My main issue now is knowing which adapter matches which adapter on the board I.E in Tvheadend what would I set as /dev/dvb/adapter0's master tuner. Presumably it's one of 3,4,5 or 7 but how would I work this out or is trial and error the only way?

**Comment by tvhdeeptho** [comment]
Try first to first use only the masters 0,2,4,6. Then add 1,3,5,7 as the slaves:
for adapter 1,  adapter 0 is the master tuner. For adapter 3, 2 is the master tuner and so on.

And crazycat's suggestion of disabling power save is also essential due to a driver bug.

I doubt that currently the slave tuners will work well because of bugs in tvheadend.
One bug is that the slave setting is lost after tvheadend is restarted. 
Also, I have not found a good way to configure this with diseqc switches (tvheadend sends
diseqc also to slave tuner, which then causes picture artefacts). For this reason, and 
because I want my equipment to power down when not in use, I only use 4 tuners.

Of course, this last point is off topic, as this issue tracker is for driver bugs. All of these 
problems can be fixed. Let us hope they will be soon.

**Comment by crazycat69** [comment]
Hint for single-cable users:
**options stid135 mode=1 rfsource=1**

rfsource can be 1-4
all 8 adapters work from selected input + can control voltage, 22KHz tone and pass diseqc command.

**Comment by StormOli** [comment]
Maybe I'm in the wrong mode? I have 4 cables from 4 separate LNBs going directly to the 4 inputs of the 6909x card.  What I was hoping for is for tuner 0,2,4 and 6 to be the masters with 1,3,5 and 7 being the respective slaves.  
Am I better off being in mode 0 and does that mean adapters are not linked to an input and simply choose the correct one based on frequency and polarity? If so how would you configure this setup in tvheadend?

**Comment by crazycat69** [comment]
you need mode 1

options dvb-core dvb_powerdown_on_sleep=0
options stid135 mode=1

**Comment by tvhdeeptho** [comment]
You mention that your tuners directly connect to LNBs. (which satellites connected to which tuners? What type of LNBs?).

Perhaps this is a really silly remark, but
- if 5.0W is connected to the "third" input (input 2 when counting from 0), 
then you will only be able to tune to it on tuner 4 and 5
-or perhaps you have diseqc switches in between and forgot to  mention?
Which switches?

**Comment by StormOli** [comment]
I have 1 satellite with 6 hybrid LNBs.  2 go into a SkyQ box and the other 4 go into the 6909x.  
What I'm looking for is to be able to stream 8 channels from 28.2E bearing in mind 0/1, 2/3, 4/5 and 6/7 must be tuned together.
I've managed to sort of get things working with adding retune to 1 in tvheadend. It does seem a bit hit and miss and I'm still getting some strange errors though like the driver seeming to crash with the following

```

[  +1.025494] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.024010] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.019869] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.024088] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023737] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023919] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.024198] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[Mar 7 19:29] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +0.000430] i2c i2c-0: stid135_read_status: fe_stid135_get_band_power_demod_not_locked error 18 !
[  +1.023392] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.024135] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023875] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023764] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023928] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023989] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023869] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023957] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023867] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023981] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.024016] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
[  +1.023871] TBSECP3 driver 0000:00:02.0: i2c xfer timeout
```

**Comment by StormOli** [comment]
The more I look into this the more I think my issues are related to those of @tvhdeeptho - I've got all my muxes scanned and services mapped to channels. The system is effectively setup but it took a brute force approach as sometimes a scan will work and the next time it won't.
I think the main issue is continuity errors as now I have all my channels they are unwatchable as there will be a video and/or audio error every minute or more caused by a continuity error.
My signal strength is around -33dbm and SNR ranges is around 15/16db

**Comment by tvhdeeptho** [comment]
@StormOli 
For your setup, mode 1 would allow you to watch 4 channels, and possibly 4 more. It depends on 
the order in which tvheadend selects tuners. I think it should be possible to configure the card in 
mode 0, and then you will achieve what you want (8 independent tuners).
Mode 0 claims to support both quattro and quad,  but you need to test it to know if it actually 
works.

From a hardware point of view: As 6090x has a wide band tuner, you could probably also use 2 cables from the skyQ wideband output. I understand that you need this for your SkyQ box, but it would be an interesting experiment to see if it works. Unfortunately,  tvheadend probably does not support wide band tuners yet.

Your last error report with the i2c xfer timeout points to another problem. I only had these problems
once: when I was experimenting with linux and with bios settings regarding the power saving feature
ASPM on the pci-express bus. In my setup, I tested various ASPM features in the bios.
linux also has aspm features, so there are lot of combinations possible and I tried a few.

What works for me is bios aspm set to "auto" (whatever that means) and linux pci_aspm disabled by adding "pcie_aspm=off" to the boot command line.

What also worked is bios aspm set to some specific values (don't remember), and linux aspm enable.
In this case I noticed some "corrected pcie errors" in the kernel log file. So I tried to get rid of those 
just to see if it affected the problems of these tickets.

During my experiments, I also tried the combination "bios set to some specific aspm value" and 
"linux aspm disabled". This produced picture for a short time, then a a majro lock up and errors like
TBSECP3 driver 0000:00:02.0: i2c xfer timeout

So concretely I advise you to check your bios settings and try altering some settings. 
Also try with and without pcie_aspm=off on the kernel command line and see if it makes a difference.
The simplest test would be to try and turn off aspm completely.

With the current card and the current tvheadend, I do have pictures and I can use 4 tuners.
It does not always work perfectly, because of the bug reported here, and because of problems in
tvheadend, but at least the basic functionality is 95% ok.

**Comment by StormOli** [comment]
@tvhdeeptho 
Thanks so much for all the info and advice.  I think I finally have a setup, whilst not perfect, I'm happy with.
I switched back into mode 0 and can confirm I appear to have 8 independent tuners working.
I think I can trace most of my issues down to a strange "feature" that's either Tvheadend or driver related, I'm not sure.  Basically I'm running tvheadend in a Bhyve VM with PCIe passthru.  By changing the VM to having 1 cpu and locking this to a physical core running at 100% all the time it seems to have solved 95% of my issues. It's obviously not ideal but instead of getting multiple continuity errors a minute, they hardly every appear if at all.

**Comment by tvhdeeptho** [comment]
Glad to hear about your progress. Your "solution" means that only one thread can run at a time, which affects the details of how things run. It is probably more a matter of luck, because threads can still block each other.

Out of curiosity: what is your primary operating system? Do you run a linux VM in windows or in linux?
 
I hope the tvheadend bugs will be solved soon.

**Comment by StormOli** [comment]
I hope the bugs will be solved soon as well as I'm still in tvheadend hell.  As you suspected, limiting the number of threads has caused other issues such as long lockups.
So I now have the choice of lots of continuity errors or a tvheadend backend that will freeze all the time.
My primary OS is Freenas (FreeBSD). Tvheadend is running in an Ubuntu 18.04 VM via bhyve.
I've tried disabling SpeedStep on the CPU and disabled CPU C State support. I thought stopping the CPU from changing frequency might be similar to having a core running at 100% but this hasn't seemed to have had any effect.
I think next on the list will be to try cutting out the virtualization but I'll need to get another hard disk for this.

**Comment by tvhdeeptho** [comment]
I doubt there is a problem that can be solved by disabling speed step. 
I would advise starting with all epg grabbing disabled, just to simplify things and see 
if you still have problems (is the problem with  pci-xpress pasthrough or with tvheeadend?
The test may tell you). 

Is the combination freebsd.linux a well tested one (do other people use it)?
If possible, try running tvheadend natively first (e.g., install Ubuntu on an external disk. 
It could help you track down the problem.

A last thing which may help: use tvheadend 4.2. It seems to be much better, but is perhaps missing
some features + the channel database is incompatible and you will need to start from zero.
It is worth a try.

**Comment by Krobar** [comment]
StormOli, Did you ever resolve the issues with the 6909X? 

Is the very similar Digital Devices SX8 likely to be any better?

**Comment by crazycat69** [comment]
What issues ?

**Comment by Krobar** [comment]
The continuity error issues within a VM. Have seen this behaviour before when using legacy interrupts but taking a guess it would use MSI by default with a fancy new card like the 6909X.

**Comment by crazycat69** [comment]
This not related to dvb driver.

**Comment by sharukhislam** [comment]
Hi i have a TBS 6909x Octa card. I have my single KU-Band LNB setup on two Dish. I selected Mode 1 but individual input for tuners not working what can i do?
