### ISSUE TITLE
Any modulation system can stop functioning

### ISSUE THREAD

**Issue by tvhdeeptho** [tbsdtv/media_build#19]
This issue may be related to #16, or not.

At some point all dvb-S2 transponders o ASTRA-2 stop functioning, whereas DVB-S
transponders are still working.

This occurs in mode=1. A cable connected to connector 0 runs to a a 4 port 
diseqc switch which connects to 4 lnbs (13.0E, 19.2E, 23.5E and 28.5E).
28.5E is connected to diseqc A. All other tuners are initially enabled in tvheadend 
and connect to another dish. When I noticed the problem, I first disabled all tuners 
except tuner0 in tvheadend to make experimenting easier
At this point it became clear that only dvb-s was working. There are no multistreams 
that can be received with this dish, so I do not know if multistream still works at this point

Unloading tbsecp3 and stid135 and reloading them fixes the problem.

**Comment by tvhdeeptho** [comment]
The first log file is a mix from tvheadend and kernel messages in time order,
Lines like  estimate_band_power_demod_not_locked: DEEPTHO: tuner=4 agcrfin1=255d agcrfin0=255d agc1ref=88d agciqin1=85d agciqin0=87d agciqin=21847d POWER_IREF=95 gain_analogx1000=37370d VGLNAgainMode=0d error=0 Pbandx1000=10130
provide input on RF/AGC/ parameters during the probem. 
The value of Pbandx1000 should be ignored as it is wrongly logged.
[problem.txt](https://github.com/tbsdtv/media_build/files/2974423/problem.txt)

For comparison, here are log files obtained after reloading the drivers.
In this case all channels work.
[after_module_reload.txt](https://github.com/tbsdtv/media_build/files/2974424/after_module_reload.txt)

When the channel does not appear usually, this results in a line with " stid135_set_parameters: not locked, band rf_power"
On the other hand a successfule tune results in a line "locked !"

Compare a bad tune and a good tune line:
GOOD:  
Mar 16 20:04:17 streacom kernel: [64233.514152] estimate_band_power_demod_not_locked: DEEPTHO: tuner=4 agcrfin1=130d agcrfin0=80d agc1ref=88d agciqin1=73d agciqin0=238d agciqin=18926d POWER_IREF=95 gain_analogx1000=61259d VGLNAgainMode=0d error=0 Pbandx1000=4294952897

BAD:
Mar 16 19:36:39 streacom kernel: [62575.900336] estimate_band_power_demod_not_locked: DEEPTHO: tuner=4 agcrfin1=131d agcrfin0=141d agc1ref=88d agciqin1=73d agciqin0=87d agciqin=18775d POWER_IREF=95 gain_analogx1000=61237d VGLNAgainMode=0d error=0 Pbandx1000=4294952899

These values seem pretty similar (for the most significant bytes). So it seems the RF path 
is OK. This is to be expected as the DVB-S channels are ok. 
The log files show not much else of interest: no errors from the drivers, but tvheadend 
does nothing.

**Comment by tvhdeeptho** [comment]
I have now also encountered a situation where none of the dvb systems (DVB-S, DVB-S2, multistream)
work anymore. The tuner seems to lock, but no data is received from the device.

**Comment by Neolo** [comment]
Same problem https://github.com/tbsdtv/media_build/issues/31
sorry, but seems nobody cares here.
Did you try their closed drivers? http://www.tbsdtv.com/forum/viewtopic.php?f=86&t=9875
