### ISSUE TITLE
TBS6985 problems with DISEQC

### ISSUE THREAD

**Issue by Wieter** [tbsdtv/media_build#21]
Dear developers,
Thanks for your open-source driver!
I tried using it with our TBS6985 (DVB-S2) connected to a 2-channel multiswitch (A: 19.2E, B: 23.5E).
However, a strange issue arises: not all muxes are detected or tuned correctly.
For example, the 12187.50H mux gets detected when scanning in the 23.5E network attached to DISEQC port B, however it shows the channels of the mux 12187.50H corresponding to DISEQC port A!
This makes me think the switching between DISEQC ports is not correctly done.
This was not an issue in the previous driver I used (proprietary from TBS: v160405), also this is not an issue when attaching a temporary USB  DVB-S tuner (TeVii S660).
I'm running tvheadend version 4.3-1288~g66d6161c5, on kernel 4.9.0-9-amd64 (Debian 4.9.168-1+deb9u2). 

For now I'm returning to the old proprietary drivers, which seem to still work fine.

**Comment by caveman99** [comment]
Try setting 'DiseqC repeats' to 2 or 3 in the tuner settings of TVHeadend - some switches do not read the pulses reliably.

**Comment by crazycat69** [comment]
tone burst or diseqc 1.0 ?

**Comment by Wieter** [comment]
@caveman99 thanks for your suggestion. I tried various DiseqC repeats (1-4), unfortunately to no avail.
For the other (temporary) DVB-S tuner, as well as the proprietary drivers, a 'DiseqC repeats' of 0 works perfectly (for >3 years). 
@crazycat69 The multiswitch is a TRIAX TMS 9x16P, labelled with the marking **DiSEqC 2.0**.
However, when I look at the spec sheet online, it states: Switch commands 13/18 V, 0/22 kHz, **DiSEqC 1.0**

**Comment by crazycat69** [comment]
so you must setup tvh as 4-port commited switch (diseqc 1.0/2.0)

**Comment by Wieter** [comment]
I tried setting the 'Sattelite config' to '4-Port switch (universal LNB)', with on AA the 19.2E- and AB the 23.5E-network. It failed to tune (no input detected). Also in combination with up to 5 retries. Switching AA and AB, or using any perturbation including BA, BB failed. Just for completeness I also tried Unicable I and II.
