### ISSUE TITLE
Build fails on zoran_device.c

### ISSUE THREAD

**Issue by waxhead** [tbsdtv/media_build#22]
Hi,

I really don't know how to work through fixing this, however latest attempt to compile the OS driver for my tbs card results in the following error and failure:

  CC [M]  /home/pete/repo-os-tbs/media_build/v4l/zoran_driver.o
/home/pete/repo-os-tbs/media_build/v4l/zoran_device.c: In function 'zoran_reap_stat_com':
/home/pete/repo-os-tbs/media_build/v4l/zoran_device.c:1154:3: error: implicit declaration of function 'v4l2_get_timestamp'; did you mean 'skb_get_timestamp'? [-Werror=implicit-function-declaration]
   v4l2_get_timestamp(&buffer->bs.timestamp);
   ^~~~~~~~~~~~~~~~~~
   skb_get_timestamp
  CC [M]  /home/pete/repo-os-tbs/media_build/v4l/zoran_card.o
  CC [M]  /home/pete/repo-os-tbs/media_build/v4l/videocodec.o
  CC [M]  /home/pete/repo-os-tbs/media_build/v4l/zr36050.o
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/pete/repo-os-tbs/media_build/v4l/zoran_device.o' failed
make[3]: *** [/home/pete/repo-os-tbs/media_build/v4l/zoran_device.o] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:1551: recipe for target '_module_/home/pete/repo-os-tbs/media_build/v4l' failed
make[2]: *** [_module_/home/pete/repo-os-tbs/media_build/v4l] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.15.0-42-generic'
Makefile:51: recipe for target 'default' failed
make[1]: *** [default] Error 2
make[1]: Leaving directory '/home/pete/repo-os-tbs/media_build/v4l'
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 2
build failed at ./build line 547

Is there a way to build and ignore errors like this?

Thanks.

Peter.

**Comment by crazycat69** [comment]
Maybe need update your local media_build repo ? Zoran driver deprecated and was removed
aa63c3fe5252e34a7a342d5eb7a0686d35f4d6d4
78eccfa404ec982e1302930cb7f45756ab404a3c

I compile without issues on Ubuntu 18.04 with 4.15 kernel.

**Comment by waxhead** [comment]
Thanks, I did a git pull before running the build script.

I did it just then again and it says it's all up to date.

I might clone it again just to be sure.

**Comment by waxhead** [comment]
OK ,confirmed, builds fine with clean clone of repo.

**Comment by waxhead** [comment]
Compiles fine.
