### ISSUE TITLE
TBS6909 - switched DiSEqC Sat numbers

### ISSUE THREAD

**Issue by KlausReinhard** [tbsdtv/media_build#25]
Dear developer,
I currently run a system with two 6590 and two 6909 cards, they are connected to a DiSEqC-Switch (EXR2998) with Sat A on S19E2 and Sat B on S13E0.
Tuning the 6590 card is corresponding to spec, finding transponders under SatA/SatB. But when tuning the 6909 card, the sat number seems to be switched. I'm using mumudvb to tune.
6590: sat_number=1 --> S19E2, sat_number=2 --> S13E0
BUT
6909: sat_number=1 -->S13E0, sat_number=2 --> S19E2

Strangely, tuning works also for  
6590: sat_number=3 --> S19E2, sat_number=4 --> S13E0
BUT
6909: sat_number=3 -->S13E0, sat_number=4 --> S19E2

How can I make card behaviour consistent, tuning same satellite on same setting?

thx in advance

**Comment by crazycat69** [comment]
mxl58x mode=1 ?

**Comment by KlausReinhard** [comment]
of course ;-)

**Comment by crazycat69** [comment]
8b21aec510b64e866709288ad21d3e86d8bfc40b

**Comment by KlausReinhard** [comment]
OK, does that mean this fix does not support unicable (mode=2) since you removed a couple of lines for mode=2 (e.g. line 803/804 - shouldn't only line 804 disappear, same for 827)

still need unicable support ;-)

**Comment by crazycat69** [comment]
Unicable support is application level.
For  driver this just custom direct connection mode. Use rfsource (1-4) option for single-cable connection for mode 1.

**options mxl58x mode=1 rfsource=1**

**Comment by KlausReinhard** [comment]
satellite tuning with above settings in mxl58x.conf does not work using a unicable switch. Using old driver with mode=2 support results in successful tuning.

Anything I have to be aware off?

Using 6909 card and Kathrein switch EXD1524

thx for any help/support

**Comment by crazycat69** [comment]
maybe connected to wrong input ? old mode 2 is mode=1 rfsource=4

**Comment by KlausReinhard** [comment]
Does rfsource refer to input of TBS card, unicable is connected to input3 (0-3) as requested in user manual. Does rfsource=4 expect the unicable to be connected to input3 etc. (rfsource=1 --> input0) which has to be configured regarding expected dvb cards connectivity?

For above setting tuning works for unicable connected to input3 of TBS6909. will try also now diseqc settings and whether switched satellites issue is resolved with new driver. Will report probably tomorrow

thx

**Comment by crazycat69** [comment]
Added mode 2 for compatibility (work like mode=1 rfsource=4). For mxl58x (6909) and stid135 (6909x)
3f8a7f6b69fce805fd9513d29791af437c6d2346
a5b570364449649eff89232d7088e1afaf6dfa72

**Comment by KlausReinhard** [comment]
works also for diseqc configurations

thx for the fix

**Comment by Neolo** [comment]
Diseqc switching not working properly when just mode=1 set and input RF is split via splitter and connected 4 cables in each tuner input. Tuner stops switching V/H and satellites on multiswitch after several CH being watched.
