### ISSUE TITLE
deliver binaries as pre-compiled artifact (e.g. deb package)

### ISSUE THREAD

**Issue by Bonifatius94** [tbsdtv/media_build#26]
It would be nice to have some versioning and artifact management (e.g. CI build pipeline), so users can download and deploy pre-compiled binaries. This would be especially useful for non-geek users that are not familiar with linux kernel stuff etc., but need this driver to run their TV system.

I could also help you a bit at setting up the build pipeline because I've got quite some experience as a software engineer.

**Comment by crazycat69** [comment]
https://github.com/jasmin-j/media-build-dkms
I will try this later also :)

**Comment by Bonifatius94** [comment]
Cool stuff. Good luck with it :)

**Comment by ShaheedHaque** [comment]
Was there ever any progress on DKMS support?
