### ISSUE TITLE
TBS 6522 occasionally uninstalling TV driver

### ISSUE THREAD

**Issue by Bonifatius94** [tbsdtv/media_build#27]
Hello, I'm using this software to run a standalone installation of TBS 6522 hardware in combination with tvheadend + kodi software (all on a single machine with Ubuntu 18.04).

My issue is that this driver occasionally uninstalls, so the /dev/dvb device is not mounted anymore after reboot. Restarting the PC does not help. The only way to fix this issue would be rebuilding and reinstalling the driver which is kind of annoying.

Could you please fix this issue and tag a stable version? This would be great :) Thank you very much in advance.

**Comment by crazycat69** [comment]
Not uninstall, just auto kernel update - so need rebuild & install media drivers for updated kernel.
Or just disable automatic kernel updates.

**Comment by Bonifatius94** [comment]
Sounds like a plan. Thank you very much for your advice :)
