### ISSUE TITLE
TBS 5520SE on raspbian

### ISSUE THREAD

**Issue by hagaygo** [tbsdtv/media_build#28]
Hi

Got raspbian buster on RPI2 , running tvheadend 4.3 (latest unstable).

Tvheadend doesn't pick up the TBS 5520SE (not shown under Dvb input , lsusb shows it).

Tried as instructed to compile the drivers.

After a long time of (About 35-40 minutes, no errors as far i could tell) i rebooted.

Not only the TBS is not shown , my 2 other USB dongles (DVBT) are now not shown (good thing i made a backup of the system).

I am not a linux expert, any pointers ? (preferably a debian package for raspbian :) )

Does the TBS5520SE supported at all by this drivers ?

Thanks in advance.

**Comment by victorvhpg** [comment]
any update? 
same happens here

**Comment by hagaygo** [comment]
Bottom line , no , but you can read more here :

https://github.com/tbsdtv/linux_media/issues/177

**Comment by tbsiptv** [comment]
Hi for RPI2 please use this package :
# wget http://www.tbsdtv.com/download/document/linux/media_build-rpi-2020-01-02.tar.bz2
# sudo rm -rf /lib/modules/`uname -r`/kernel/drivers/media/
#tar jxvf media_build-rpi-2020-01-02.tar.bz2
#cd media_build 
#./install.sh 
#reboot
