### ISSUE TITLE
Unable to build for archlinux mainline kernel 5.5

### ISSUE THREAD

**Issue by BytEvil** [tbsdtv/media_build#32]
Hi, friends! Unable to build drivers for archlinux mainline kernel 5.5.:

> /build/tbs_new/src/media_build/v4l/tas2101.c: In function 'tas2101_spi_read':
/build/tbs_new/src/media_build/v4l/tas2101.c:325:45: error: dereferencing pointer to incomplete type 'struct ecp3_info'
  325 |   priv->cfg->read_properties(adapter,ecp3inf->reg, &(ecp3inf->data));
      |                                             ^~
/build/tbs_new/src/media_build/v4l/tas2101.c: At top level:
/build/tbs_new/src/media_build/v4l/tas2101.c:328:62: warning: 'struct ecp3_info' declared inside parameter list will not be visible outside of this definition or declaration
  328 | static void tas2101_spi_write(struct dvb_frontend *fe,struct ecp3_info *ecp3inf)
      |                                                              ^~~~~~~~~
/build/tbs_new/src/media_build/v4l/tas2101.c: In function 'tas2101_spi_write':
/build/tbs_new/src/media_build/v4l/tas2101.c:333:46: error: dereferencing pointer to incomplete type 'struct ecp3_info'
  333 |   priv->cfg->write_properties(adapter,ecp3inf->reg, ecp3inf->data);
      |                                              ^~
/build/tbs_new/src/media_build/v4l/tas2101.c: In function 'tas2101_attach':
/build/tbs_new/src/media_build/v4l/tas2101.c:663:1: warning: label 'err1' defined but not used [-Wunused-label]
  663 | err1:
      | ^~~~
/build/tbs_new/src/media_build/v4l/tas2101.c: At top level:
/build/tbs_new/src/media_build/v4l/tas2101.c:927:3: error: 'struct dvb_frontend_ops' has no member named 'spi_read'
  927 |  .spi_read   = tas2101_spi_read,
      |   ^~~~~~~~
/build/tbs_new/src/media_build/v4l/tas2101.c:927:16: error: initialization of 'int (*)(struct dvb_frontend *, enum fe_status *)' from incompatible pointer type 'void (*)(struct dvb_frontend *, struct ecp3_info *)' [-Werror=incompatible-pointer-types]
  927 |  .spi_read   = tas2101_spi_read,
      |                ^~~~~~~~~~~~~~~~
/build/tbs_new/src/media_build/v4l/tas2101.c:927:16: note: (near initialization for 'tas2101_ops.read_status')
/build/tbs_new/src/media_build/v4l/tas2101.c:928:3: error: 'struct dvb_frontend_ops' has no member named 'spi_write'
  928 |  .spi_write   = tas2101_spi_write,
      |   ^~~~~~~~~
/build/tbs_new/src/media_build/v4l/tas2101.c:928:17: error: initialization of 'int (*)(struct dvb_frontend *, u32 *)' {aka 'int (*)(struct dvb_frontend *, unsigned int *)'} from incompatible pointer type 'void (*)(struct dvb_frontend *, struct ecp3_info *)' [-Werror=incompatible-pointer-types]
  928 |  .spi_write   = tas2101_spi_write,
      |                 ^~~~~~~~~~~~~~~~~
/build/tbs_new/src/media_build/v4l/tas2101.c:928:17: note: (near initialization for 'tas2101_ops.read_ber')
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:266: /build/tbs_new/src/media_build/v4l/tas2101.o] Ошибка 1
make[1]: *** [Makefile:1693: /build/tbs_new/src/media_build/v4l] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.5.0-rc7-1-mainline/build'

**Comment by crazycat69** [comment]
Updated, try again

**Comment by BytEvil** [comment]
Hi, @crazycat69. First building error:
```
/build/tbs_new/src/media_build/v4l/compat.h: In function 'i2c_new_secondary_device':
/build/tbs_new/src/media_build/v4l/compat.h:2437:9: error: implicit declaration of function 'i2c_new_dummy' [-Werror=implicit-function-declaration]
 2437 |  return i2c_new_dummy(client->adapter, addr);
      |         ^~~~~~~~~~~~~
/build/tbs_new/src/media_build/v4l/compat.h:2437:9: warning: returning 'int' from a function with return type 'struct i2c_client *' makes pointer from integer without a cast [-Wint-conversion]
 2437 |  return i2c_new_dummy(client->adapter, addr);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
After my small modifications in /v4l/compat.h:

```
/* of_property_read_u32_index is available since Kernel 3.10. For older Kernels
 * this will not compile */
#if LINUX_VERSION_CODE <= KERNEL_VERSION(5, 3, 0)
#ifdef NEED_I2C_NEW_SECONDARY_DEV
#include <linux/i2c.h>
static inline struct i2c_client *i2c_new_secondary_device(struct i2c_client *client,
```
and
```
#ifdef NEED_I2C_NEW_DUMMY_DEVICE
#include <linux/i2c.h>
#define i2c_new_dummy_device(adap, addr) (i2c_new_dummy(adap, addr) ? : (struct i2c_client *)ERR_PTR(-ENODEV))
#endif

```
 i have a new error:
```
/build/tbs_new/src/media_build/v4l/mn88436.c: In function 'mn88436_probe':
/build/tbs_new/src/media_build/v4l/mn88436.c:1380:19: error: implicit declaration of function 'i2c_new_dummy' [-Werror=implicit-function-declaration]
 1380 |  dev->client[1] = i2c_new_dummy(client->adapter,0x10);
      |                   ^~~~~~~~~~~~~
```
after disabling this module from build i have another error:
```
/build/tbs_new/src/media_build/v4l/tbs_pcie.c: In function 'tbs_audio_register':
/build/tbs_new/src/media_build/v4l/tbs_pcie.c:1552:65: error: implicit declaration of function 'snd_dma_pci_data' [-Werror=implicit-function-declaration]
 1552 |   snd_pcm_lib_preallocate_pages_for_all(pcm, SNDRV_DMA_TYPE_DEV,snd_dma_pci_data(dev->pdev), TBS_AUDIO_CELL_SIZE*4, TBS_AUDIO_CELL_SIZE*4);
      |                                                                 ^~~~~~~~~~~~~~~~
```

**Comment by alanswanson** [comment]
So, https://git.linuxtv.org//media_build.git does not (yet) have compatibility functions for;

i2c_new_dummy() replaced by devm_i2c_new_dummy_device() that returns ERR_PTR. See [replacement](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b8f5fe3bc5b9318d95770a09a480c31aced20cd2) and old [removal](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2c2f00ab1641895183488ff2bce53c415344fb87).

i2c_new_secondary_device() changed to i2c_new_ancillary_device() that returns ERR_PTR. See [change](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=af80559b4d9cd481c63505edbe425ff6bad4ab8d).

Not sure of upstreaming changes to media_build git.

The snd_dma_pci_data macro was depreciated and removed. See [removal](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b65f131b8f47b399a0635f028af3888f8c741ae1). Since its just a macro, required change in pci/tbscapture/tbs_pcie.c from _snd_dma_pci_data(dev->pdev)_ to _&dev->pdev->dev_ will support older kernels.

**Comment by crazycat69** [comment]
upd

**Comment by BytEvil** [comment]
tested, nothing changed...

**Comment by BytEvil** [comment]
compiled just fine after this [patch](https://github.com/BytEvil/media_build/commit/f62aeed062786566268c066dd005757809588640).

**Comment by crazycat69** [comment]
Thanks. Your fixes now in [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media)
https://github.com/tbsdtv/linux_media/commit/e29db5d8e23a3bb95d88669a6109ab956d02064e
https://github.com/tbsdtv/linux_media/commit/983f41316d9839252c5c892541454d25bd80210c

**Comment by BytEvil** [comment]
@crazycat69 и тебе спасибо за помощь! ;)
