### ISSUE TITLE
Latest version breaks i915!

### ISSUE THREAD

**Issue by pchristyUK** [tbsdtv/media_build#33]
System: Slackware64-current. Hardware: VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

Before installing TBS-fork driver:

Kernel-5.4.30 dmesg | grep i915
[    6.753039] i915 0000:00:02.0: vgaarb: deactivate vga console
[    6.753818] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    6.755940] [drm] Initialized i915 1.6.0 20190822 for 0000:00:02.0 on minor 0
[    6.757401] snd_hda_intel 0000:00:03.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    6.797757] fbcon: i915drmfb (fb0) is primary device
[    6.845283] i915 0000:00:02.0: fb0: i915drmfb frame buffer device

After installing driver:

Kernel-5.4.30 dmesg | grep i915
[    7.410856] i915: Unknown symbol cec_notifier_put (err -2)
[    7.464552] i915: Unknown symbol cec_notifier_put (err -2)
[   16.064911] i915: Unknown symbol cec_notifier_put (err -2)
[   16.079576] i915: Unknown symbol cec_notifier_put (err -2)

Installing the latest TBS-fork driver completely breaks the driver. Trying to play any video at all (TV, youtube, local files) causes freezing and black flashes every few seconds. The seems to happen with all 5.4.X kernels. It was OK until a couple of months ago. (Only just updated the kernel)

TBS-fork built with recommended allyesconfig. Can it be built without cec?

-- 
Pete Christy

**Comment by crazycat69** [comment]
Look like i915 module have some generic HDMI CEC support in 5.4+ kernels
https://github.com/tbsdtv/linux_media/commit/5558f3d535c54e5ca39df7896022b103360a9ab1#diff-a07ceb1685db788927a0efbdfbef007d

CEC core is part of media driver and recompiled in media_build
https://github.com/tbsdtv/linux_media/tree/latest/drivers/media/cec

After this commit not compatible with old kernel modules which depend from CEC CORE
https://github.com/tbsdtv/linux_media/commit/e6111647934562849ba052052ffbc673b935a9fe#diff-2db74465f596d36e0335af85c3fba987

So wait solution from mainstream media_buidl or try downgrade kernel.

**Comment by pchristyUK** [comment]
Thank you for your reply. I am not a programmer or developer, though I am reasonably computer literate, and able to follow (and even write) *simple* stuff in C.

Kernels 5.4+ are the LTS line, and already quite old. 5.5+ is currently marked as "stable", and 5.6 has been released. Going back to older kernels is not an option.

Earlier this year (probably late January or early February), I had no problem building and installing this driver with kernel 5.4.14. At the time it worked perfectly. Now, if I try to build it against 5.4.14 I have exactly the same problem.

This tells me that something has changed in this driver that has broken compatibility. Slackware already comes with v4l-utils-1.18 (15th of Feb) and has no problems until the TBS driver is installed. Looking at the v4l github page, I can see a lot of cec related commits since the middle of March, though I have no idea if these are relevant or not.

I believe that using git it ought to be possible to check out an earlier version of this driver - say before the most recent changes (mid-February?) but I am uncertain how to do this. Can you advise? This may help to pinpoint the change that has caused the problem.

-- 
Pete
