### ISSUE TITLE
Problem TBS6522 with Openpli2pc

### ISSUE THREAD

**Issue by rachid-tvsat** [tbsdtv/media_build#34]
hi friends,
i have a tbs6522 card and ubuntu 18.04.4 LTS, i install driver card linux from here
https://github.com/tbsdtv/linux_media/wiki

i install tvheadend without problems, the card worked good,
https://www3.0zz0.com/2020/04/21/22/146693627.png
https://www5.0zz0.com/2020/04/21/22/219344927.png

But when I installed Openpli2pc from here
http://github.com/ag1455/OpenPLi-PC
https://www9.0zz0.com/2020/04/21/22/510117670.png

the card worked good with dvb-t/t2
https://www5.0zz0.com/2020/04/21/23/676760710.png

but not worked with dvb-s/s2
https://www4.0zz0.com/2020/04/19/18/145497637.png

$ cat /usr/local/e2/etc/tuxbox/nim_sockets
NIM Socket 0:
Type: DVB-T2
Name: TurboSight TBS 6522 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T
Has_Outputs: no
Frontend_Device: 0

NIM Socket 1:
Type: DVB-S2
Name: TurboSight TBS 6522 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T
Has_Outputs: no
Frontend_Device: 1

NIM Socket 0:
Type: DVB-T2
Name: TurboSight TBS 6522 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T
Has_Outputs: no
Frontend_Device: 0

NIM Socket 1:
Type: DVB-S2
Name: TurboSight TBS 6522 DVB-S/S2/S2X/T/T2/C/C2/ISDB-T
Has_Outputs: no
Frontend_Device: 1

**Comment by crazycat69** [comment]
look like enigma2 not support multi-frontend adapters, so Frontend_Device is adapter number and always used frontend0

**Comment by rachid-tvsat** [comment]
Thank you for answering my friend, can I run just DVB-S/S2 on this card?
sorry for bad english

**Comment by crazycat69** [comment]
you can rename/swap frontend device files or compile dvb drivers from my [media_build](https://bitbucket.org/CrazyCat/media_build) when first sattelite frontend. second - ter/cable.

I will try [ag1455/Openpli2pc ](https://github.com/ag1455/OpenPLi-PC) later, maybe make some patch for multi-frontend adapters support.

**Comment by rachid-tvsat** [comment]
As for the way I did not understand you well, could you simplify me more

Well my friend, I am waiting for you.

Thank you

**Comment by crazycat69** [comment]
options tbsecp3 swapfe=1
