### ISSUE TITLE
nvidia_drm prevented from loading since Linux 5.6

### ISSUE THREAD

**Issue by Chance4us** [tbsdtv/media_build#36]
Since Kernel "SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux" the "nvidia_drm" module is prevented from loading by "/lib/modules/5.6.0-1-amd64/kernel/drivers/media/cec/cec.ko" module.

I manged it by replacing cec.ko through the original "/lib/modules/5.6.0-1-amd64/kernel/drivers/media/cec/cec.ko". So nvidia_drm module finally loaded.

Is there any way not to have to do this replacing?

**Comment by tbsiptv** [comment]
which nvidia driver version you are using ? as we success install the DVB  driver and nvidia driver 
5.6.3  , 440.33.01

**Comment by Chance4us** [comment]
When I created the report I had a slightly older driver than now. Since then I have updated the nvidia driver to the following new version. I will try the new driver soon and report here.
![nvidia](https://user-images.githubusercontent.com/45902449/82726075-fcbc6080-9ce1-11ea-9d93-20aae3acbc9c.png)
