### ISSUE TITLE
A problem in oscam with Openpli2pc

### ISSUE THREAD

**Issue by Nadjm-Gharib** [tbsdtv/media_build#37]
Hello
I have a card sky star2 express and I installed enigma2 Openpli2pc on ubuntu 18.04
(dvbapi) ERROR: Can't open device /dev/dvb/adapter0/ca0 
ca0 is not in this path

**Comment by tbsiptv** [comment]
Hi sir 

which TBS card you are using , if the card have no CAM slot there is no ca0 device 

Thanks

kind Regards
