### ISSUE TITLE
amdgpu

### ISSUE THREAD

**Issue by clear-sky** [tbsdtv/media_build#43]
hi all
first thing first thanks for your great work!

my dvb card is tbs6922 and was happy with it sevral years  with nvidia 1050ti
i replaced my 1050 nvidia with amd 5500xt !
tried to install driver in arch linux with AUR

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tbs-linux_media-git

this way had worked for me sevral years with nvidia
but with amdgpu (open source driver) after installation system does not boot
 
in fact system starts boot and during boot process crashes
i was locky besause after boot crash could login as root with ctrl + F2

lsmod command helped me 
i listed working modules before and after driver installation and found needed modules for tbs 6922
then removed all driver and installed only needed modules and it worked!
this modules are :
av201x.ko.gz    mc.ko.gz               tas2101.ko.gz           videobuf2-vmalloc.ko.gz
cx24117.ko.gz   saa716x_core.ko.gz     videobuf2-common.ko.gz  videodev.ko.gz
dvb-core.ko.gz  saa716x_tbs-dvb.ko.gz  videobuf2-memops.ko.gz

**Comment by steven1758** [comment]
hi sir 

thanks so much for the information ,when you install the driver do you delete the media folder ?

Thanks

**Comment by clear-sky** [comment]
thanks for reply
no this driver is installed in this path:
/lib/modules/5.9.8-2-MANJARO/updates/tbs/
but will try your idea

**Comment by clear-sky** [comment]
i deleted media folder after driver install and run depmod -a
/usr/lib/modules/5.9.11-2-MANJARO/kernel/drivers/media/
but no success!
thanks for answer and your notice!

**Comment by clear-sky** [comment]
thanks for your great work
today i updated driver and saw problem have been solved!
thanks again
