### ISSUE TITLE
tbs6280 no status information for adapter 1

### ISSUE THREAD

**Issue by FosterSM** [tbsdtv/media_build#47]
Both adapters on my tbs6280 tune to tv channels and produce valid pictures and sound.
However I can only get status, signal strength etc. from adaptor 0.
the front end consists of a cxd2820r and tda18212.
any idea why this should be so ?

examples of femon output when both adapters correctly tuned:

FeMon: error 0 adapter 0 status 1f | signal d56d | snr 0051 | ber 00000000 | unc 00000000 | FE_HAS_LOCK

FeMon: error 0 adapter 1 status 00 | signal 0000 | snr 0000 | ber 00000000 | unc 00000000 | FE_NOT_LOCKED

Thanks

**Comment by crazycat69** [comment]
no lock - so no strength/snr

**Comment by FosterSM** [comment]
Thats what is reported but picture and sound are fine on that adapter ?? Which device does the ioctl get routed to in the kernel, I could instrument the code to find out more information ?.
Thanks

**Comment by FosterSM** [comment]
From strace the ioctls other than FE_READ_STATUS are returning EAGAIN is that expected ?

ioctl(6, FE_READ_STATUS, 0x7fff3c3a2eb8) = 0
ioctl(6, FE_READ_SIGNAL_STRENGTH, 0x7fff3c3a2eb4) = -1 EAGAIN (Resource temporarily unavailable)
ioctl(6, FE_READ_SNR, 0x7fff3c3a2eb6)   = -1 EAGAIN (Resource temporarily unavailable)
ioctl(6, FE_READ_BER, 0x7fff3c3a2eb0)   = -1 EAGAIN (Resource temporarily unavailable)
ioctl(6, FE_READ_UNCORRECTED_BLOCKS, 0x7fff3c3a2eac) = -1 EAGAIN (Resource temporarily unavailable)
write(2, "FeMon: error 0 adapter 1 status "..., 106FeMon: error 0 adapter 1 status 00 | signal 0000 | snr 0000 | ber 00000000 | unc 00000000 | FE_NOT_LOCKED
