### ISSUE TITLE
Many compilation errors

### ISSUE THREAD

**Issue by NowDeer** [tbsdtv/media_build#48]
The driver cannot be built due to many compilation errors.

/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:339:12: error: initialization of 'int (*)(struct dma_buf *, struct dma_buf_attachment *)' from incompatible pointer type 'int (*)(struct dma_buf *, struct device *, struct dma_buf_attachment *)' [-Werror=incompatible-pointer-types]
  .attach = vb2_vmalloc_dmabuf_ops_attach,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:339:12: note: (near initialization for 'vb2_vmalloc_dmabuf_ops.attach')
/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:343:3: error: 'const struct dma_buf_ops' has no member named 'map'; did you mean 'mmap'?
  .map = vb2_vmalloc_dmabuf_ops_kmap,
   ^~~
   mmap
/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:343:9: error: initialization of 'void (*)(struct dma_buf *)' from incompatible pointer type 'void * (*)(struct dma_buf *, long unsigned int)' [-Werror=incompatible-pointer-types]
  .map = vb2_vmalloc_dmabuf_ops_kmap,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:343:9: note: (near initialization for 'vb2_vmalloc_dmabuf_ops.release')
/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:344:3: error: 'const struct dma_buf_ops' has no member named 'map_atomic'
  .map_atomic = vb2_vmalloc_dmabuf_ops_kmap,
   ^~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:344:16: error: initialization of 'int (*)(struct dma_buf *, enum dma_data_direction)' from incompatible pointer type 'void * (*)(struct dma_buf *, long unsigned int)' [-Werror=incompatible-pointer-types]
  .map_atomic = vb2_vmalloc_dmabuf_ops_kmap,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-vmalloc.c:344:16: note: (near initialization for 'vb2_vmalloc_dmabuf_ops.begin_cpu_access')
cc1: some warnings being treated as errors
  CC [M]  /home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.o
…
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:515:12: error: initialization of 'int (*)(struct dma_buf *, struct dma_buf_attachment *)' from incompatible pointer type 'int (*)(struct dma_buf *, struct device *, struct dma_buf_attachment *)' [-Werror=incompatible-pointer-types]
  .attach = vb2_dma_sg_dmabuf_ops_attach,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:515:12: note: (near initialization for 'vb2_dma_sg_dmabuf_ops.attach')
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:521:3: error: 'const struct dma_buf_ops' has no member named 'map'; did you mean 'mmap'?
  .map = vb2_dma_sg_dmabuf_ops_kmap,
   ^~~
   mmap
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:521:9: error: initialization of 'int (*)(struct dma_buf *, struct vm_area_struct *)' from incompatible pointer type 'void * (*)(struct dma_buf *, long unsigned int)' [-Werror=incompatible-pointer-types]
  .map = vb2_dma_sg_dmabuf_ops_kmap,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:521:9: note: (near initialization for 'vb2_dma_sg_dmabuf_ops.mmap')
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:522:3: error: 'const struct dma_buf_ops' has no member named 'map_atomic'
  .map_atomic = vb2_dma_sg_dmabuf_ops_kmap,
   ^~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:522:16: error: initialization of 'void * (*)(struct dma_buf *)' from incompatible pointer type 'void * (*)(struct dma_buf *, long unsigned int)' [-Werror=incompatible-pointer-types]
  .map_atomic = vb2_dma_sg_dmabuf_ops_kmap,
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/luke/TBS_GIT/media_build/v4l/videobuf2-dma-sg.c:522:16: note: (near initialization for 'vb2_dma_sg_dmabuf_ops.vmap')
cc1: some warnings being treated as errors

**Comment by crazycat69** [comment]
kernel version, arch ?

**Comment by NowDeer** [comment]
4.18.0-305.12.1.el8_4.x86_64

**Comment by crazycat69** [comment]
This fucking CentOS 4.18 kernel with forced 4.20+ patches.
Try comment lines in backports\backport.txt:
**[4.20.255]
add v4.20_access_ok.patch**

**Comment by NowDeer** [comment]
Umm... 
I comment above lines, but the error is the same.

**Comment by crazycat69** [comment]
**make cleanall** before build

**Comment by waxhead** [comment]
Hi I'm having the same issue with the errors on Ubuntu:

5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by waxhead** [comment]
OK, my bad on that, make cleanall resolved my issue.  Sorry for the noise.

**Comment by Neolo** [comment]
> Ubuntu 20.04LTS shipped with 5.4 kernel, next was HWE updates 5.8 and 5.11 now.

No, there is no 5.11 in 20.04 LTS HWE Development at the moment top version was 5.14. But it doesn’t really matter, because I had a backup of 4.15 and it wont compile there either. I did distro upgrade all the way to normal 21.04 and it overwrote kernel with 5.11 and then it compiled.

**Comment by crazycat69** [comment]
Today again tested on Ubuntu 16.04 LTS with 4.4 and 4.15 kernels - success
And Ubuntu 20.04 LTS with 5.4 and 5.11 - again success :)

Where you find this fucking kernel pacckages ?:)

**Comment by Neolo** [comment]
> Today again tested on Ubuntu 16.04 LTS with 4.4 and 4.15 kernels - success And Ubuntu 20.04 LTS with 5.4 and 5.11 - again success :) And Debian 11 with 5.10
> 
> Where you find this fucking kernel packages ?:)

apt-get update
That’s where. Log shows you errors, so instead of blaming the kernels, why don’t you just fix code to satisfy it?

**Comment by crazycat69** [comment]
linux-headers-5.4.0-852109090909-generic wtf ?:)
