### ISSUE TITLE
libpcre2-posix issue

### ISSUE THREAD

**Issue by pchristyUK** [tbsdtv/media_build#50]
Build fails on Slackware64-current, kernel 5.15:
"error while loading shared libraries: libpcre2-posix.so.2: cannot open shared object file: No such file or directory"

This version of Slackware uses: "/usr/lib64/libpcre2-posix.so.3"

The TBS media_build-2021-06-07 also fails:
"media_build/v4l/bttv-gpio.c:64:19: error: initialization of 'void (*)(struct device *)' from incompatible pointer type 'int (*)(struct device *)' [-Werror=incompatible-pointer-types]
   64 |         .remove = bttv_sub_remove,
      |                   ^~~~~~~~~~~~~~~
media_build/v4l/bttv-gpio.c:64:19: note: (near initialization for 'bttv_sub_bus_type.remove')
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:277: media_build/v4l/bttv-gpio.o] Error 1"

although that does build under kernel-5.14.15 on the same system.

-- 
Pete C

**Comment by crazycat69** [comment]
[media_build](https://github.com/tbsdtv/media_build) and [linux_media](https://github.com/tbsdtv/linux_media) just updated, must be compatible with 4.4 - 5.15 kernels

**Comment by pchristyUK** [comment]
Well, it isn't! The TBS version of media_build (2021-06-07) fails under 5.15 as noted above, but does build OK under 5.14.15. Is this the same as the version here? Can I just take this version and run their install.sh script on it?

I can't tell if your version builds OK or not because it never gets that far due to the libpcre2-posix version bump.

-- 
Pete

**Comment by crazycat69** [comment]
"online" media_build always better for "fresh" kernel & distrib :) "offline" media_builds targeted for "redhat-centos" :)

**Comment by pchristyUK** [comment]
Thanks for your advice! However, I'm still a bit confused as to the correct build procedure here. I have instructions for the original TBS-fork - which built fine until the libpcre2 version bump mentioned above, and for the "offline" version, which again built fine until kernel 5.15. However, looking at the "install.sh" script here ("online" version?), I'm a bit puzzled by it.

Is this (online) version intended to be built "stand-alone" or as part of TBS-fork? If it is, what - precisely - is the correct build procedure?

TIA,

-- 
Pete

**Comment by pchristyUK** [comment]
Thanks for your help and advice! I finally got it to build and install, though I did it by first installing to a "fake" directory and creating a Slackware package from that. This gets around the problem that plagued me with the "offline" build method, which would over-write kernel modules even if the build had failed, rendering the system useless. (Luckily, I always keep an earlier version of the kernel for this eventuality, though it is a pain to restore the broken installation!)

I should now be able to write a "build script" to generate a Slackware package, which should completely automate the build up to the point of installation. Perfect!

-- 
Pete

**Comment by crazycat69** [comment]
now default media_build branch **extra** which install modules in updates dir (not overwrite kernel modules)

**Comment by pchristyUK** [comment]
Very sensible! I noticed that they seemed to be installing in an unexpected location.

I've now written a "slackbuild" script, which completely automates the build process for future kernel upgrades. The only "manual" part of the procedure is actually installing the resulting slackpkg. I could automate that too, but caution dictates otherwise! ;)

Of course, the ultimate solution would be for these modules to be incorporated into the kernel upstream - like many other manufacturers modules are. Is there any prospect of this happening or will licensing issues prevent it?
