### ISSUE TITLE
nouveau driver cannot load, kernel 5.11

### ISSUE THREAD

**Issue by brackleian** [tbsdtv/media_build#52]
Using stock kernel 5.11.0-38-generic. The `nouveau` module will not load if the `v4l` modules are installed. Problems with `cec` module, see extract from dmesg:
```
[    3.295357] cec: disagrees about version of symbol rc_keyup
[    3.295360] cec: Unknown symbol rc_keyup (err -22)
[    3.295645] cec: disagrees about version of symbol rc_register_device
[    3.295646] cec: Unknown symbol rc_register_device (err -22)
[    3.295649] cec: disagrees about version of symbol rc_keydown
[    3.295650] cec: Unknown symbol rc_keydown (err -22)
[    3.295658] cec: disagrees about version of symbol rc_free_device
[    3.295659] cec: Unknown symbol rc_free_device (err -22)
[    3.295665] cec: disagrees about version of symbol rc_allocate_device
[    3.295665] cec: Unknown symbol rc_allocate_device (err -22)
[    3.295952] cec: disagrees about version of symbol rc_unregister_device
[    3.295952] cec: Unknown symbol rc_unregister_device (err -22)
```
The specific module I need from `v4l` is `tbsecp3`, which supports the TBS6904 tuner card.

Any suggestions for a work-around would be most welcome.

**Comment by crazycat69** [comment]
use extra branch and disable IR RC support in V4L DVB drivers, see install.sh
https://github.com/tbsdtv/media_build/blob/extra/install.sh

**Comment by brackleian** [comment]
Hi CrazyCat,

On Fri, 07 Jan 2022 20:13:29 +0000 (UTC)
CrazyCat ***@***.***> wrote:

> use extra branch and disable IR RC support in V4L DVB drivers, see install.sh
> https://github.com/tbsdtv/media_build/blob/extra/install.sh

Thanks a million, that worked fine.

My build method was:
	clone 'extra' branch
	edit 'build' script to modify config just before main 'make'
Don't know if there is a more efficient way?

Are there any plans to fix the problem and merge into 'master'?

Cheers,
Austin (alias 'brackleian')

**Comment by brackleian** [comment]
Problem: nouveau now drives my video card HDMI output with video, but no audio. Could this be related?
