### ISSUE TITLE
Simplify Installation Process

### ISSUE THREAD

**Issue by Bonifatius94** [tbsdtv/media_build#53]
Hi everyone,

wouldn't it be nice to deploy your software via some package managers like apt? I'm not an apt packaging expert, but having to compile the source code is really inconvenient.

And another thing. Ubuntu seems to kick your kernel module out every 3 months after their big kernel update. Could you please provide information on how to permanently install your software? I don't want to repair my TV driver several times a year, it's really inconvenient.

Best wishes
Marco

**Comment by Bonifatius94** [comment]
I've created some scripts. Please have a look at https://github.com/Bonifatius94/tbs_driver_setup

**Comment by Saentist** [comment]
> I've created some scripts. Please have a look at https://github.com/Bonifatius94/tbs_driver_setup

DKMS option is needed.

**Comment by Bonifatius94** [comment]
Hey @Saentist 😄

Sorry, I'm not so familiar with kernel module development. Could you please explain to me what you mean by your dkms suggestion? (I've had a quick read telling me that it's about re-installing kernel modules after OS updates, right?) 😉

My scripts were hacked together pretty badly on a single afternoon, so there's no rocket science to be expected 😂

Best wishes, Marco

**Comment by Hoeze** [comment]
@Bonifatius94 We would need a DKMS package of this like you can see here:
https://aur.archlinux.org/cgit/aur.git/tree/?h=tbs-linux_media-git-dkms
Basically, whenever the kernel is being updated, DKMS re-compiles the tbsdvb modules against that version.
Advantages:
- You only install the driver package 
- A single out-of-tree module is much less invasive than replacing the whole linux media tree

**Comment by Bonifatius94** [comment]
> We would need a DKMS package of this like you can see here:

@Hoeze Thanks for your reply :smile: Do you know how to set up such a DKMS packaging? This kernel stuff is really out of my scope :sweat_smile: I'm quite good with Bash scripting and setting up CI/CD pipelines, though and wanna contribute to this to learn about it :wink:

**Comment by Hoeze** [comment]
Unfortunately no, but I think the [PKGBUILD file](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tbs-linux_media-git-dkms) in the linked repo will be a great starting point :)
I'm trying the same for my server...

**Comment by Bonifatius94** [comment]
Hmmm ok, wanna call on Discord? MarcoTroester#9199

**Comment by Hoeze** [comment]
@Bonifatius94 I finally had time to look into it and found a repo that we can build on.
I changed some details to it and here is my current progress:
https://github.com/Hoeze/TBS_DTV_DKMS

This should do what we want, but unfortunately it fails with this:
```bash
make[3]: /bin/sh: Argument list too long
make[3]: *** [scripts/Makefile.build:467: /var/lib/dkms/TBS_DTV_DKMS/github.com_tbsdtv/build/media_build/v4l/modules.order] Error 127
make[2]: *** [Makefile:1881: /var/lib/dkms/TBS_DTV_DKMS/github.com_tbsdtv/build/media_build/v4l] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.15.0-47-generic'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/var/lib/dkms/TBS_DTV_DKMS/github.com_tbsdtv/build/media_build/v4l'
make: *** [Makefile:26: all] Error 2
```

The reason is that DKMS copies the source files to `/var/lib/dkms/TBS_DTV_DKMS/github.com_tbsdtv/build`.
Using this prefix causes very long file paths and makes the build process fail.
If you call `cd /usr/src/TBS_DTV_DKMS/ && sh make.sh`, the build process succeeds.

Now I am a bit clueless how to solve that issue.
If you like, you can have a try and see how to solve this path-too-long issue.

**Comment by Bonifatius94** [comment]
@Hoeze Damn, nice work man :smile: I'm going to look into it and see if there's a fix :joy: (what a silly bug ...)

**Comment by Bonifatius94** [comment]
Could it be that some bash command is 130k characters? WTF???
https://stackoverflow.com/questions/11475221/why-do-i-get-bin-sh-argument-list-too-long-when-passing-quoted-arguments

**Comment by Bonifatius94** [comment]
Idk man, something has to go very wrong here ... :joy: :joy: :joy: :joy: :joy:

**Comment by Bonifatius94** [comment]
Yes indeed, the line stated in the error message seems to pass down all args the script is called with which can be a lot: https://github.com/tbsdtv/media_build/blob/9a225f4da01944fd34e1f9cf113da0d0d6f40820/v4l/Makefile#L467

The question is: Why is it producing so many args and why does this 4 characters less root folder name work? :thinking:

**Comment by Hoeze** [comment]
Seems to be same like here:
https://github.com/tbsdtv/media_build/issues/46

@crazycat any idea?
