### ISSUE TITLE
install.sh can lead to problems when upgrading

### ISSUE THREAD

**Issue by deeptho** [tbsdtv/media_build#54]
install.sh now stored modules in .../updates/extra insstead of in .../kernel/drivers/media
This can lead to duplicate modules (an old and a new one) being installed if the user 
has used an older version of media_build before or if media_build updates a module 
which also exists in a standard kernel

**Comment by deeptho** [comment]
It seems that modprobe attaches a higher priority to modules in updates.... 
So everything should work, but it can still be confusing

**Comment by crazycat69** [comment]
module loading order in module dependency list, generated by **depmod** util

**Comment by deeptho** [comment]
Yes, I have adopted this system now as well for the blindscan drivers (not yet made public). Hopefully fewer complaints from users. We will see.
