### ISSUE TITLE
Cannot build with current Arch standard or LTS kernel

### ISSUE THREAD

**Issue by Krobar** [tbsdtv/media_build#61]
I get the error below with both the 6.1 LTS and 6.3 Arch kernels:
`  LD [M]  /home/media_build/v4l/snd-bt87x.o
  MODPOST /home/media_build/v4l/Module.symvers
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_map_get' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_map_register' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_map_unregister' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_g_keycode_from_table' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_keyup' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_repeat' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_keydown' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_keydown_notimeout' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_allocate_device' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_free_device' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'devm_rc_allocate_device' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_register_device' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'devm_rc_register_device' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'rc_unregister_device' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_event_store' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_event_store_edge' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_event_store_with_timeout' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_event_store_with_filter' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_event_set_idle' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_event_handle' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_gen_manchester' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_gen_pd' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_gen_pl' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_encode_scancode' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_encode_carrier' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_handler_register' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'ir_raw_handler_unregister' exported twice. Previous export was in vmlinux
ERROR: modpost: /home/media_build/v4l/rc-core: 'lirc_scancode_event' exported twice. Previous export was in vmlinux
make[3]: *** [scripts/Makefile.modpost:126: /home/media_build/v4l/Module.symvers] Error 1
make[2]: *** [Makefile:1964: modpost] Error 2
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/home/media_build/v4l'
make: *** [Makefile:26: all] Error 2
build failed at ./build line 554`

Are these kernels unsupported or am I doing something wrong?

**Comment by crazycat69** [comment]
use **install.sh** for configure/complile/install media modules
