### ISSUE TITLE
Compile faults in shipped linux-media.tar.bz2

### ISSUE THREAD

**Issue by Borim7** [tbsdtv/media_build#62]
During the complation of the drivers the linux-media.tar.bz2 is downloaded from this repository, the currently shipped version trigger compile errors in following files:
* ./linux/drivers/media/tuners/mxl603.c
* ./linux/drivers/media/dvb-frontends/si2183.c
* ./linux/drivers/media/dvb-frontends/mtv23x.c
* ./linux/drivers/media/dvb-frontends/gx1503.c
* ./linux/drivers/media/dvb-frontends/m88rs6060.c

The problem is always the same: The function signature of the remove function used for initialization of the `struct i2c_driver` does not match the `struct i2c_driver` type.

For example in mxl603.c the function is `static void mxl603_remove(struct i2c_client *client)`, but the struct need a remove function returning an `int`. Change the function to `static int mxl603_remove(struct i2c_client *client)` and return always 0, fix this problem.

Can you please update the linux-media.tar.bz2?

My system is 
````
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Kernel: 5.15.0-76-generic
````

**Comment by crazycat69** [comment]
Before compilation **media_build** scripts apply backport patches for older kernels
For your certain case applied [backports/v6.0_i2c_remove_tbs.patch](https://github.com/tbsdtv/media_build/blob/extra/backports/v6.0_i2c_remove_tbs.patch) for kernels < 6.1

**Comment by Borim7** [comment]
Thanks for the hint, with this patch it worked.

In the end I switched from master to extra branch, as the patch is only available on extra.
