### ISSUE TITLE
unable to build ubuntu mainline kernel 4.16.6

### ISSUE THREAD

**Issue by eelstrebor** [tbsdtv/media_build#7]
Preparing to compile for kernel version 4.16.6
File not found: /lib/modules/4.16.6-041606-generic/build/.config at ./scripts/make_kconfig.pl line 33, <IN> line 4.
Syncing with dir ../../media
make[2]: Leaving directory '/home/user/Downloads/Linux/media_build/linux'
Preparing to compile for kernel version 4.16.6
File not found: /lib/modules/4.16.6-041606-generic/build/.config at ./scripts/make_kconfig.pl line 33, <IN> line 4.
make[1]: *** No rule to make target '.config', needed by '.myconfig'.  Stop.
make[1]: Leaving directory '/home/user/Downloads/Linux/media_build/v4l'
Makefile:26: recipe for target 'all' failed
make: *** [all] Error 2
root@server2:/home/user/Downloads/Linux/media_build# exit
logout
user@server2:~/Downloads/Linux$ ls /lib/modules/4.16.6-041606-generic/build
ls: cannot access '/lib/modules/4.16.6-041606-generic/build': No such file or directory
user@server2:~/Downloads/Linux$ ls /lib/modules/4.16.6-041606-generic/
initrd             modules.builtin      modules.devname  modules.symbols.bin
kernel             modules.builtin.bin  modules.order    vdso
modules.alias      modules.dep          modules.softdep
modules.alias.bin  modules.dep.bin      modules.symbols

**Comment by crazycat69** [comment]
install kernel header.

**Comment by svalcken** [comment]
Possible equal Problem. My Kernel has an another Version with the kernel sources. Version: 4.15.0-22-generic means uname. Patches and Pathes means 4.13.0-37-generic. Whats wrong?
Here are Buildlog.
******************
* Start building *
******************
make -C /tbs_opensource2/media_build/v4l allyesconfig
make[1]: Verzeichnis „/tbs_opensource2/media_build/v4l“ wird betreten
make[2]: Entering directory '/tbs_opensource2/media_build/linux'
Syncing with dir ../media/
Applying patches for kernel 4.13.0-37-generic
patch -s -f -N -p1 -i ../backports/api_version.patch
patch -s -f -N -p1 -i ../backports/pr_fmt.patch
patch -s -f -N -p1 -i ../backports/debug.patch
patch -s -f -N -p1 -i ../backports/drx39xxj.patch
patch -s -f -N -p1 -i ../backports/v4.14_compiler_h.patch
patch -s -f -N -p1 -i ../backports/v4.14_saa7146_timer_cast.patch
patch -s -f -N -p1 -i ../backports/v4.14_module_param_call.patch
Patched drivers/media/dvb-core/dvbdev.c
Patched drivers/media/v4l2-core/v4l2-dev.c
Patched drivers/media/rc/rc-main.c
Syncing with dir ../media/
make[2]: Leaving directory '/tbs_opensource2/media_build/linux'
./scripts/make_kconfig.pl /lib/modules/4.13.0-37-generic/build /lib/modules/4.13.0-37-generic/build 1
Preparing to compile for kernel version 4.13.0
File not found: /lib/modules/4.13.0-37-generic/build/.config at ./scripts/make_kconfig.pl line 33, <IN> line 4.
Makefile:383: recipe for target 'allyesconfig' failed
make[1]: *** [allyesconfig] Error 2
make[1]: Verzeichnis „/tbs_opensource2/media_build/v4l“ wird verlassen
Makefile:26: recipe for target 'allyesconfig' failed
make: *** [allyesconfig] Error 2
can't select all drivers at ./build line 546
root@sr001:/tbs_opensource2/media_build# uname -a
Linux sr001 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@sr001:/tbs_opensource2/media_build# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

**Comment by crazycat69** [comment]
Kernel headers not installed.
Run ./build script which check required packages for driver build.
