### ISSUE TITLE
Problems with building in debian 12

### ISSUE THREAD

**Issue by Fomtom24** [tbsdtv/media_build#72]
git clone - ok
make dir DIR=../media - ok
make allyesconfig - problem.
after apt upgrade I changed the kernel from 6.1.0-18-amd64 to 6.1.0-20-amd64. 
Now I got this:
make[2]: Leaving directory '/home/fomtom/tbs6902/media_build/linux'
./scripts/make_kconfig.pl /lib/modules/6.1.0-18-amd64/build /lib/modules/6.1.0-18-amd64/build 1
Preparing to compile for kernel version 6.1.0
File not found: /lib/modules/6.1.0-18-amd64/build/.config at ./scripts/make_kconfig.pl line 33, <IN> line 4.
make[1]: *** [Makefile:376: allyesconfig] Fehler 2
make[1]: Verzeichnis „/home/fomtom/tbs6902/media_build/v4l“ wird verlassen
make: *** [Makefile:26: allyesconfig] Fehler 2
===================
There is no directory /lib/modules/6.1.0-18-amd64/ - ist removed.

Where I can change this?

**Comment by crazycat69** [comment]
kerbel headers for 6.1.0-20-amd64 not installed

**Comment by Fomtom24** [comment]
They are installed:
root@vdr01:/home/fomtom# apt-get install linux-headers-$(uname -r)
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
linux-headers-6.1.0-20-amd64 ist schon die neueste Version (6.1.85-1).
linux-headers-6.1.0-20-amd64 wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

**Comment by Fomtom24** [comment]
I had this problem on the former ubuntu-machine with three different kernels:
"Make" did it allways only for one - the "oldest" - kernel.
So I removed the 6.1.0-18-Kernel complete in my actual debian-machine. The 6.1.0-20 is the only kernel - with kernel-headers.
