### ISSUE TITLE
linux-6.9 support 

### ISSUE THREAD

**Issue by Serafean** [tbsdtv/media_build#74]
I tried to make this work with linux 6.9. I'm sure I did it completely wrong, but it worked... here goes.
added patches to backport: https://github.com/tbsdtv/media_build/compare/master...Serafean:tbs_media_build:v6.9?expand=1

and two patches to apply to the v4l directory.
[netup.txt](https://github.com/user-attachments/files/15859235/netup.txt)
[msi2500.txt](https://github.com/user-attachments/files/15859236/msi2500.txt)

If you give me guidelines to rework properly, I' game.

**Comment by crazycat69** [comment]
[tbsdtv/media_build](https://github.com/tbsdtv/media_build) and [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media) updated for 6.9 compatibility.
Please check

**Comment by Serafean** [comment]
On Tuesday 2 July 2024 00:45:50 CEST CrazyCat wrote:
> [tbsdtv/media_build](https://github.com/tbsdtv/media_build) and
> [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media) updated for 6.9
> compatibility. Please check

Just built with 6.9.7. 
Thanks!
