### ISSUE TITLE
linux-6.10 support

### ISSUE THREAD

**Issue by Serafean** [tbsdtv/media_build#76]
Once again, I threw stuff at it until I made it build.

Related to : https://github.com/torvalds/linux/commit/068a95ef3945033b5355e50fecea18737680d43d
[v6.9-i2c-mux.txt](https://github.com/user-attachments/files/16418410/v6.9-i2c-mux.txt)
Manual edits required at:
si2183.c:1737 
tas2971.c:{297,300}
gx1133.c:{813,815}
gx1503.c:519

I2C_CLASS_SPD removed:
[v6.9-unidvb.txt](https://github.com/user-attachments/files/16418432/v6.9-unidvb.txt)

 removal of follow_pfn() 
 https://github.com/torvalds/linux/commit/cb10c28ac82c9b7a5e9b3b1dc7157036c20c36dd
set CONFIG_VIDEOBUF_DMA_CONTIG=n  (Not fighting that one...)

__assign_str 2nd parameter removed:
 https://github.com/torvalds/linux/commit/2c92ca849fcc6ee7d0c358e9959abc9f58661aea
[v6.9-assign_str.txt](https://github.com/user-attachments/files/16418407/v6.9-assign_str.txt)

**Comment by Delitants** [comment]
Entering directory '/usr/src/linux-headers-6.5.0-342405280420-generic'

  ERROR: Kernel configuration is invalid.
         include/generated/autoconf.h or include/config/auto.conf are missing.
         Run 'make oldconfig && make prepare' on kernel src to fix it.

6.5.0-342405280420-generic

**Comment by crazycat69** [comment]
[tbsdtv/media_build](https://github.com/tbsdtv/media_build) and [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media) updated for 6.10 compatibility.
Please check

**Comment by Serafean** [comment]
Compiles fine. Thank you!
