### ISSUE TITLE
linux 6.12 support (and 6.11.11)

### ISSUE THREAD

**Issue by Serafean** [tbsdtv/media_build#78]
6.12.3 landed in Gentoo, and I got interested...
Made it build, seems to work.

for 6.11.11:
v4l/serial_ir.c
#include <linux/io.h>

 6.12.3
unaligned.h moved
[5f60d5f6bbc12e782fac78110b0ee62698f3b576](https://github.com/torvalds/linux/commit/5f60d5f6bbc12e782fac78110b0ee62698f3b576)

find ./linux/ -type f  -exec sed -i "s-asm/unaligned.h-linux/unaligned.h-" {} \;

fd memory safety:
https://github.com/torvalds/linux/commit/0f25f0e4efaeb68086f7e65c442f2d648b21736f#diff-a80f6d75d873c883963a6b27d2081888218ecd2e1816fafc19d18f5ec0e03450
https://github.com/torvalds/linux/commit/0f25f0e4efaeb68086f7e65c442f2d648b21736f/#diff-95ac6ebb90e2af4d079dc2055bd36ec5760e26dc91b996d101cdd3f7cc1903a6

ll_seek removal
https://github.com/torvalds/linux/commit/cb787f4ac0c2e439ea8d7e6387b925f74576bdf8#diff-f930a3bc02e7a3809f1ab814f3af1316160dd99e6e6ee28e186f979591c84fea
https://github.com/torvalds/linux/commit/cb787f4ac0c2e439ea8d7e6387b925f74576bdf8#diff-3feeb8f63409d7de7e63b94d0620c0fcb34e90ac1580399c6b4fbc5f6ceb8cde
https://github.com/torvalds/linux/commit/cb787f4ac0c2e439ea8d7e6387b925f74576bdf8#diff-f04e19e8ff1de3af1e6c2e8f84b0465c78fc50a435035e0508d051c8506d25b3
https://github.com/torvalds/linux/commit/cb787f4ac0c2e439ea8d7e6387b925f74576bdf8#diff-d4d71dc3856275982f6c81c8d0fb8b91a0392cbfd4a2bfdc125dd608256dfe59

dma_set_max_seg_size no longer returns
https://github.com/torvalds/linux/commit/334304ac2baca7f3e821c47cf5129d9#diff-c0271079162acec50f29513e823d57f907acc3194c378f32a0c576766c83ee30

**Comment by crazycat69** [comment]
[tbsdtv/media_build](https://github.com/tbsdtv/media_build) and [tbsdtv/linux_media](https://github.com/tbsdtv/linux_media) updated for 6.12 compatibility.
Please check

**Comment by Serafean** [comment]
almost. 

v4l/serial_ir.c: missing include
#include <linux/io.h>

is missing. Sorry, wasn't clear that's needed for 6.12 too. The rest works fine. Thanks.

**Comment by crazycat69** [comment]
Thanks, fixed now.
https://github.com/tbsdtv/linux_media/commit/fb40feb6f2bca59c5cd240ece5276213e9f0c9ce

**Comment by Serafean** [comment]
Thanks! Just compiled against 6.12.5.
