### ISSUE TITLE
hunk FAILED tbs 6909x ubuntu 20, fail make allyesconfig

### ISSUE THREAD

**Issue by hjulianm** [tbsdtv/media_build#80]
Hello.

My ubuntu 18 was working fine. But, I decided to install ubuntu 20 on December 13, 2024. Now I'm having errors from "make allyesconfig". A few days ago I had ubuntu 20 without driver problems. I don't know what happened, please help.

I have used https://help.cesbo.com/misc/tools-and-utilities/dvb/tbs-driver#check-driver before, automatic and manual, and everything worked.

`root@ubuntutv:/usr/src/media_build# make allyesconfig
make -C /usr/src/media_build/v4l allyesconfig
make[1]: Entering directory '/usr/src/media_build/v4l'
No version yet, using 5.4.0-202-generic
make[2]: Entering directory '/usr/src/media_build/linux'
Syncing with dir ../../media
Applying patches for kernel 5.4.0-202-generic
patch -s -f -N -p1 -i ../backports/api_version.patch
patch -s -f -N -p1 -i ../backports/pr_fmt.patch
patch -s -f -N -p1 -i ../backports/debug.patch
patch -s -f -N -p1 -i ../backports/drx39xxj.patch
patch -s -f -N -p1 -i ../backports/ccs.patch
patch -s -f -N -p1 -i ../backports/rc-cec.patch
patch -s -f -N -p1 -i ../backports/v6.11-unaligned.patch
patch -s -f -N -p1 -i ../backports/v6.11-fd.patch
patch -s -f -N -p1 -i ../backports/v6.10_bt8xx.patch
patch -s -f -N -p1 -i ../backports/v6.9_i2c_mux.patch
patch -s -f -N -p1 -i ../backports/v6.9_i2c_mux_tbs.patch
patch -s -f -N -p1 -i ../backports/v6.9_assign_str.patch
patch -s -f -N -p1 -i ../backports/v6.8-ccs.patch
patch -s -f -N -p1 -i ../backports/v6.8-spi.patch
patch -s -f -N -p1 -i ../backports/v6.7-cec.patch
patch -s -f -N -p1 -i ../backports/v6.5_pcm_copy.patch
patch -s -f -N -p1 -i ../backports/v6.5_dvb_math.patch
patch -s -f -N -p1 -i ../backports/v6.3_class_create.patch
1 out of 1 hunk FAILED
make[2]: *** [Makefile:135: apply_patches] Error 1
make[2]: Leaving directory '/usr/src/media_build/linux'
make[1]: *** [Makefile:375: allyesconfig] Error 2
make[1]: Leaving directory '/usr/src/media_build/v4l'
make: *** [Makefile:26: allyesconfig] Error 2
root@ubuntutv:/usr/src/media_build#
`
...
make
make install

curl -L http://www.tbsdtv.com/download/document/linux/tbs-tuner-firmwares_v1.0.tar.bz2 | tar -C /lib/firmware/ -jxf -
-----

ls /dev/dvb
No such file or directory

/home/ubuntutv# lspci -v | grep Multimedia
0b:00.0 Multimedia controller: TBS Technologies DVB Tuner PCIe Card

0b:00.0 Multimedia controller: TBS Technologies DVB Tuner PCIe Card
        Subsystem: Device 6909:0010
        Physical Slot: 2
        Flags: bus master, fast devsel, latency 0, IRQ 5, NUMA node 0
        Memory at f7fc0000 (32-bit, non-prefetchable) [size=256K]
        Capabilities: [50] Power Management version 3
        Capabilities: [70] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [90] Express Endpoint, MSI 00
        Capabilities: [100] Device Serial Number 00-00-00-00-00-00-00-00

**Comment by crazycat69** [comment]
fixed
https://github.com/tbsdtv/media_build/commit/dedbd386cc037808a1ba3a0fa495a118df581db7
